"""Stable errors exposed by the commercial policy interface."""


class CommercialPolicyError(RuntimeError):
    def __init__(self, code, message, *, status_code=400, details=None):
        super().__init__(message)
        self.code = str(code)
        self.message = str(message)
        self.status_code = int(status_code)
        self.details = details or {}


POLICY_INVALID = "COMMERCIAL_POLICY_INVALID"
VALIDATION_FAILED = "COMMERCIAL_POLICY_VALIDATION_FAILED"
POLICY_STALE = "COMMERCIAL_POLICY_STALE"
VALIDATION_OBSOLETE = "COMMERCIAL_POLICY_VALIDATION_OBSOLETE"
SCHEDULE_CONFLICT = "COMMERCIAL_POLICY_SCHEDULE_CONFLICT"
PROVIDER_UNAVAILABLE = "COMMERCIAL_POLICY_PROVIDER_UNAVAILABLE"
REFERENCE_IN_USE = "COMMERCIAL_POLICY_REFERENCE_IN_USE"
AUDIT_FAILED = "COMMERCIAL_POLICY_AUDIT_FAILED"
OFFER_NOT_SELLABLE = "OFFER_NOT_SELLABLE"
BUYER_NOT_AUTHORIZED = "BUYER_NOT_AUTHORIZED"
TRANSITION_NOT_ALLOWED = "TRANSITION_NOT_ALLOWED"
DECISION_REQUIRED = "COMMERCIAL_POLICY_DECISION_REQUIRED"
QUOTE_EXPIRED = "QUOTE_EXPIRED"
QUOTE_NOT_AVAILABLE = "QUOTE_NOT_AVAILABLE"
NO_HEALTHY_PROVIDER = "NO_HEALTHY_PROVIDER"
PAYMENT_MISMATCH = "PAYMENT_MISMATCH"
PROVIDER_EVENT_UNVERIFIED = "PROVIDER_EVENT_UNVERIFIED"
ACTIVATION_REVISION_CONFLICT = "ACTIVATION_REVISION_CONFLICT"
QUOTA_EXHAUSTED = "QUOTA_EXHAUSTED"
REFUND_NOT_SUPPORTED = "REFUND_NOT_SUPPORTED"
REFUND_AMOUNT_INVALID = "REFUND_AMOUNT_INVALID"
