import os
import threading
import uuid
from pathlib import Path

import pytest
from psycopg import sql

from backend.db.db_helper import PostgresDatabase
from backend.shared.audit_chain import append_audit_row, inspect_audit_chain
from backend.shared.audit_monitor import _inspect_database


def _test_database_url():
    if value := os.environ.get("TEST_DATABASE_URL"):
        return value
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if not env_path.exists():
        return ""
    for line in env_path.read_text(encoding="utf-8").splitlines():
        key, separator, value = line.partition("=")
        if separator and key.strip() == "TEST_DATABASE_URL":
            return value.strip().strip('"').strip("'")
    return ""


class _HeadRaceCursor:
    def __init__(self, cursor, release_writer, writer_committed):
        self._cursor = cursor
        self._release_writer = release_writer
        self._writer_committed = writer_committed
        self._released = False

    def execute(self, statement, parameters=None):
        normalized = " ".join(str(statement).split()).casefold()
        if (
            not self._released
            and "select chain_id, last_sequence, last_log_id, last_hash"
            in normalized
            and "from audit_chain_heads" in normalized
        ):
            self._released = True
            self._release_writer.set()
            if not self._writer_committed.wait(timeout=10):
                raise AssertionError("Concurrent audit writer did not commit in time.")
        if parameters is None:
            return self._cursor.execute(statement)
        return self._cursor.execute(statement, parameters)

    def __getattr__(self, name):
        return getattr(self._cursor, name)

    def __iter__(self):
        return iter(self._cursor)


class _HeadRaceConnection:
    def __init__(self, connection, release_writer, writer_committed):
        self._connection = connection
        self._release_writer = release_writer
        self._writer_committed = writer_committed

    def cursor(self):
        return _HeadRaceCursor(
            self._connection.cursor(),
            self._release_writer,
            self._writer_committed,
        )

    def __getattr__(self, name):
        return getattr(self._connection, name)


class _SingleConnectionDatabase:
    def __init__(self, connection):
        self._connection = connection

    def get_connection(self):
        return self._connection


def test_monitor_uses_one_snapshot_while_audit_writer_commits():
    database_url = _test_database_url()
    if not database_url:
        pytest.skip("TEST_DATABASE_URL is not configured")

    schema = f"audit_snapshot_{uuid.uuid4().hex}"
    database = PostgresDatabase(database_url)
    setup = database.get_connection()
    try:
        setup.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        setup.execute(
            sql.SQL('''CREATE TABLE {}.database_metadata (
                id INTEGER PRIMARY KEY,
                installation_id TEXT NOT NULL
            )''').format(sql.Identifier(schema))
        )
        setup.execute(
            sql.SQL('''CREATE TABLE {}.audit_chain_heads (
                chain_id TEXT PRIMARY KEY,
                last_sequence BIGINT NOT NULL,
                last_log_id BIGINT,
                last_hash TEXT NOT NULL,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )''').format(sql.Identifier(schema))
        )
        setup.execute(
            sql.SQL('''CREATE TABLE {}.audit_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chain_id TEXT NOT NULL,
                sequence BIGINT NOT NULL,
                actor_user_id TEXT,
                organization_id TEXT,
                action TEXT NOT NULL,
                target_type TEXT,
                target_id TEXT,
                ip_address TEXT,
                metadata_json TEXT,
                created_at TEXT NOT NULL,
                previous_hash TEXT NOT NULL,
                entry_hash TEXT NOT NULL,
                UNIQUE (chain_id, sequence)
            )''').format(sql.Identifier(schema))
        )
        setup.execute(
            sql.SQL('''INSERT INTO {}.database_metadata (id, installation_id)
                VALUES (1, %s)''').format(sql.Identifier(schema)),
            (f"installation-{uuid.uuid4().hex}",),
        )
        setup.commit()
    finally:
        setup.close()

    writer = None
    writer_thread = None
    writer_errors = []
    try:
        writer = database.get_connection()
        writer.execute(
            sql.SQL("SET search_path TO {}").format(sql.Identifier(schema))
        )
        writer.commit()
        append_audit_row(writer, action="audit.snapshot.seed")

        verifier = database.get_connection()
        verifier.execute(
            sql.SQL("SET search_path TO {}").format(sql.Identifier(schema))
        )
        verifier.commit()
        release_writer = threading.Event()
        writer_committed = threading.Event()

        def append_during_verification():
            try:
                if not release_writer.wait(timeout=10):
                    raise AssertionError("Audit verifier did not reach the head read.")
                append_audit_row(writer, action="audit.snapshot.concurrent")
            except BaseException as exc:  # noqa: BLE001 - propagated in the test thread
                writer_errors.append(exc)
            finally:
                writer_committed.set()

        writer_thread = threading.Thread(
            target=append_during_verification,
            daemon=True,
        )
        writer_thread.start()
        verification, checkpoint_path = _inspect_database(
            _SingleConnectionDatabase(
                _HeadRaceConnection(verifier, release_writer, writer_committed)
            )
        )
        writer_thread.join(timeout=10)

        assert not writer_thread.is_alive()
        assert writer_errors == []
        assert checkpoint_path is None
        assert verification.valid, verification.failure

        fresh = database.get_connection()
        try:
            fresh.execute(
                sql.SQL("SET search_path TO {}").format(sql.Identifier(schema))
            )
            fresh.commit()
            final_verification = inspect_audit_chain(fresh.cursor())
            assert final_verification.valid
            assert final_verification.row_count == 2
            fresh.rollback()
        finally:
            fresh.close()
    finally:
        if writer_thread is not None and writer_thread.is_alive():
            writer_committed.set()
            writer_thread.join(timeout=10)
        if writer is not None:
            writer.close()
        cleanup = database.get_connection()
        try:
            cleanup.execute(
                sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema))
            )
            cleanup.commit()
        finally:
            cleanup.close()
            database.close()
