import re

from backend.db import db_utils
from backend.db.db_helper import SQLiteDatabase
from backend.db.postgresql_features import build_postgresql_trigger_source_map

from backend.db.postgresql_schema import (
    POSTGRESQL_EXTRA_TABLES,
    compile_postgresql_baseline,
)
from backend.db.schema import MONEY_COLUMNS, SCHEMA_DINH_NGHIA
from backend.db.postgresql_types import (
    BOOLEAN_COLUMNS,
    DATE_COLUMNS,
    EPOCH_COLUMNS,
    TIMESTAMP_COLUMNS,
)
from backend.sync.queries import build_postgresql_search_filter


def test_postgresql_baseline_covers_every_canonical_table_and_column():
    compiled = compile_postgresql_baseline()
    expected_schema = {**SCHEMA_DINH_NGHIA, **POSTGRESQL_EXTRA_TABLES}
    assert set(compiled["manifest"]) == set(expected_schema)
    assert len(compiled["createTables"]) == len(expected_schema) == 45
    for table_name, table_spec in expected_schema.items():
        assert set(compiled["manifest"][table_name]["columns"]) == set(
            table_spec["columns"]
        )


def test_postgresql_baseline_has_no_sqlite_only_ddl_tokens():
    compiled = compile_postgresql_baseline()
    ddl = "\n".join(
        compiled["createTables"] + compiled["foreignKeys"] + compiled["indexes"]
    )
    forbidden = (
        "AUTOINCREMENT",
        "typeof(",
        "datetime(",
        "date(",
        " AS BLOB",
        "PRAGMA",
        "sqlite_",
    )
    for token in forbidden:
        assert token.casefold() not in ddl.casefold()
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "idx_audit_log_single_successor" in ddl


def test_postgresql_money_columns_are_bigint_and_constraints_are_named():
    compiled = compile_postgresql_baseline()
    for table_name, column_name in MONEY_COLUMNS:
        definition = compiled["manifest"][table_name]["columns"][column_name]
        assert definition.startswith("BIGINT")
    names = [
        item["name"]
        for table in compiled["manifest"].values()
        for item in table["foreignKeys"]
    ]
    assert len(names) == len(set(names))
    assert all(re.fullmatch(r"[a-z0-9_]{1,63}", name) for name in names)


def test_postgresql_decimal_business_values_use_exact_numeric_type():
    compiled = compile_postgresql_baseline()
    decimal_columns = {
        ("goi_thau", "ty_le_bao_dam_hop_dong"),
        ("goi_thau_tuy_chon_mua_them", "so_luong"),
        ("goi_thau_tuy_chon_mua_them", "ty_le"),
        ("thong_tin_mo_thau", "ty_le_giam_gia"),
        ("tieu_chi_danh_gia", "diem_toi_da"),
        ("tieu_chi_danh_gia", "trong_so"),
        ("ket_qua_danh_gia_nha_thau", "diem"),
    }
    for table_name, column_name in decimal_columns:
        assert compiled["manifest"][table_name]["columns"][column_name].startswith(
            "NUMERIC(20,4)"
        )


def test_postgresql_boolean_flags_use_native_boolean_type():
    compiled = compile_postgresql_baseline()
    mapped = {
        column_name
        for table in compiled["manifest"].values()
        for column_name, definition in table["columns"].items()
        if definition.startswith("BOOLEAN")
    }
    assert mapped == BOOLEAN_COLUMNS


def test_postgresql_business_dates_and_technical_timestamps_use_native_types():
    compiled = compile_postgresql_baseline()
    mapped_dates = set()
    mapped_timestamps = set()
    for table in compiled["manifest"].values():
        for column_name, definition in table["columns"].items():
            if definition.startswith("DATE"):
                mapped_dates.add(column_name)
            if definition.startswith("TIMESTAMPTZ"):
                mapped_timestamps.add(column_name)
    assert mapped_dates == DATE_COLUMNS
    assert mapped_timestamps == TIMESTAMP_COLUMNS
    mapped_epoch_columns = {
        column_name
        for table in compiled["manifest"].values()
        for column_name, definition in table["columns"].items()
        if column_name in EPOCH_COLUMNS and definition.startswith("BIGINT")
    }
    assert mapped_epoch_columns == EPOCH_COLUMNS


def test_postgresql_foreign_keys_are_applied_after_all_create_tables():
    compiled = compile_postgresql_baseline()
    assert compiled["foreignKeys"]
    assert all(statement.startswith("CREATE TABLE") for statement in compiled["createTables"])
    assert all(statement.startswith("ALTER TABLE") for statement in compiled["foreignKeys"])


def test_postgresql_search_indexes_use_immutable_accent_fold_expression():
    compiled = compile_postgresql_baseline()
    search_indexes = [
        statement for statement in compiled["indexes"] if "_search_trgm" in statement
    ]
    assert len(search_indexes) == 5
    assert all("bidding_immutable_unaccent" in statement for statement in search_indexes)
    assert all("concat_ws" not in statement for statement in search_indexes)


def test_postgresql_search_filter_matches_index_expression_and_tokenizes_input():
    compiled = compile_postgresql_baseline()
    index = next(
        statement
        for statement in compiled["indexes"]
        if "idx_chu_dau_tu_search_trgm" in statement
    )
    expression, parameters = build_postgresql_search_filter(
        "chu_dau_tu", "Nguyễn   Trãi"
    )
    assert parameters == [
        "(^|[[:space:][:punct:]])nguyen",
        "(^|[[:space:][:punct:]])trai",
    ]
    assert expression.count("bidding_immutable_unaccent(lower(") == 2
    indexed_expression = index.split(" USING GIN (", 1)[1].rsplit(" gin_trgm_ops", 1)[0]
    assert indexed_expression in expression


def test_postgresql_manifest_covers_every_sqlite_index_and_trigger(
    monkeypatch, tmp_path
):
    source_database = SQLiteDatabase(tmp_path / "source-manifest.db")
    monkeypatch.setattr(db_utils, "database", source_database)
    monkeypatch.setenv("ADMIN_PASSWORD", "Temporary-Manifest-Test-2026!")
    monkeypatch.setenv("ADMIN_EMAIL", "manifest@example.test")
    db_utils.khoi_tao_va_di_tru_he_thong()
    connection = source_database.get_connection()
    try:
        sqlite_indexes = {
            row[0]
            for row in connection.execute(
                """SELECT name FROM sqlite_master
                   WHERE type = 'index' AND name NOT LIKE 'sqlite_autoindex_%'"""
            ).fetchall()
        }
        sqlite_triggers = {
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type = 'trigger'"
            ).fetchall()
        }
    finally:
        connection.close()

    compiled = compile_postgresql_baseline()
    postgresql_indexes = {
        re.search(r"INDEX\s+([A-Za-z0-9_]+)", statement, re.IGNORECASE).group(1)
        for statement in compiled["indexes"]
    }
    target_artifacts = postgresql_indexes | {
        re.search(r"TRIGGER\s+([A-Za-z0-9_]+)", statement, re.IGNORECASE).group(1)
        for statement in compiled["triggers"]
    }
    trigger_mapping = build_postgresql_trigger_source_map()

    assert sqlite_indexes <= postgresql_indexes
    assert set(trigger_mapping) == sqlite_triggers
    assert set(trigger_mapping.values()) <= target_artifacts
