"""Canonical PostgreSQL schema for fresh BiddingFlow installations."""

from __future__ import annotations

import os
import re
import time
from copy import deepcopy
from hashlib import sha256

from psycopg import sql
from psycopg.errors import UndefinedColumn, UndefinedObject, UndefinedTable

from backend.db.schema import (
    HISTORICAL_SCHEMA_DINH_NGHIA,
    MONEY_COLUMNS,
    RETIRED_PROCUREMENT_CENTER_TABLES,
    SCHEMA_DINH_NGHIA,
)
from backend.contracts.contract_statuses import DEFAULT_CONTRACT_STATUSES
from backend.db.upgrades import (
    DB_SCHEMA_VERSION,
    DatabaseUpgradeContext,
    REQUIRED_POST_V64_FK_INDEXES,
    apply_database_upgrades,
    drop_retired_procurement_center_schema,
    ensure_commercial_v79_indexes,
    read_database_version,
    record_database_version,
    seed_live_payos_v80_profile,
    seed_commercial_v79,
)
from backend.shared.logging_utils import log_error


_SYSTEM_TIMESTAMP_COLUMNS = frozenset(
    {
        "created_at",
        "updated_at",
        "archived_at",
        "deleted_at",
        "left_at",
        "assigned_at",
        "ended_at",
        "closed_at",
        "finalized_at",
        "voided_at",
        "occurred_at",
        "fetched_at",
        "applied_at",
        "available_at",
        "locked_at",
        "retired_at",
        "run_at",
    }
)

_BUSINESS_TIMESTAMP_COLUMNS = frozenset(
    {
        ("ke_hoach_lcnt", "thoi_gian_dang_tai"),
        ("goi_thau", "thoi_gian_dang_tai"),
        ("goi_thau", "thoi_gian_dong_thau"),
        ("goi_thau", "thoi_gian_mo_thau"),
        ("goi_thau", "thoi_gian_mo_ehsdxtc"),
        ("goi_thau_gia_han", "thoi_gian_dong_thau"),
        ("thong_tin_mo_thau", "violation_bid_closing_at"),
        ("thong_tin_mo_thau", "violation_checked_at"),
        ("thong_tin_mo_thau_lien_danh_thanh_vien", "violation_bid_closing_at"),
        ("thong_tin_mo_thau_lien_danh_thanh_vien", "violation_checked_at"),
        ("contractor_violation_checks", "bid_closing_at"),
        ("contractor_violation_checks", "checked_at"),
        ("goi_thau_lam_ro", "thoi_gian"),
    }
)

_BIGINT_COLUMNS = frozenset(
    {
        "schema_version",
        "phien_ban",
        "sync_version",
        "row_version",
        "current_version",
        "min_available_version",
        "delete_version",
        "revision",
        "last_sequence",
        "last_log_id",
        "sequence",
        "starts_at",
        "expires_at",
        "requested_at",
        "verified_at",
        "used_at",
        "window_started_at",
        "last_seen_at",
        "idle_expires_at",
        "absolute_expires_at",
        "revoked_at",
        "privileged_reauth_at",
        "read_at",
        "chunk_index",
        "page_number",
        "char_count",
        "next_revision_index",
        "total_revisions",
    }
)


def _is_boolean_definition(definition: str) -> bool:
    compact = re.sub(r"\s+", "", definition.casefold())
    return "in(0,1)" in compact


def _strip_sqlite_type_checks(definition: str) -> str:
    definition = re.sub(
        r"typeof\([a-zA-Z0-9_]+\)\s*=\s*'integer'\s+AND\s+",
        "",
        definition,
        flags=re.IGNORECASE,
    )
    definition = re.sub(
        r"typeof\([a-zA-Z0-9_]+\)\s+IN\s*\(\s*'integer'\s*,\s*'real'\s*\)\s+AND\s+",
        "",
        definition,
        flags=re.IGNORECASE,
    )
    return definition


def postgres_column_definition(table_name: str, column_name: str, definition: str) -> str:
    """Translate a canonical column declaration without retaining SQLite quirks."""

    result = str(definition)
    if column_name == "extension_json" and "json_valid" in result:
        return (
            "TEXT NOT NULL DEFAULT '{\"schemaVersion\":1}' "
            "CHECK(jsonb_typeof(extension_json::jsonb) IS NOT NULL "
            "AND pg_column_size(extension_json) <= 65536)"
        )
    if "INTEGER PRIMARY KEY AUTOINCREMENT" in result:
        return result.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )

    result = _strip_sqlite_type_checks(result)
    result = re.sub(
        r"datetime\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", result, flags=re.IGNORECASE
    )
    result = re.sub(
        r"date\(\s*'now'\s*\)", "CURRENT_DATE", result, flags=re.IGNORECASE
    )

    if result.startswith("REAL"):
        result = "NUMERIC(20,4)" + result[len("REAL") :]
    elif result.startswith("INTEGER"):
        if (table_name, column_name) in MONEY_COLUMNS or column_name in _BIGINT_COLUMNS:
            result = "BIGINT" + result[len("INTEGER") :]
        elif _is_boolean_definition(result):
            result = "SMALLINT" + result[len("INTEGER") :]
    elif result.startswith("TEXT"):
        is_date = column_name.startswith("ngay_") or column_name in {
            "document_date",
            "issued_date",
            "effective_from",
            "effective_to",
        }
        is_timestamp = (
            column_name in _SYSTEM_TIMESTAMP_COLUMNS
            or (table_name, column_name) in _BUSINESS_TIMESTAMP_COLUMNS
        )
        if is_date:
            result = "DATE" + result[len("TEXT") :]
            result = re.sub(
                rf"\s+CHECK\(date\({re.escape(column_name)}\) IS NOT NULL\)",
                "",
                result,
                flags=re.IGNORECASE,
            )
            result = re.sub(
                rf"\s+CHECK\({re.escape(column_name)} IS NULL OR \(length\({re.escape(column_name)}\) = 10 AND date\({re.escape(column_name)}\) IS NOT NULL\)\)",
                "",
                result,
                flags=re.IGNORECASE,
            )
        elif is_timestamp:
            result = "TIMESTAMPTZ" + result[len("TEXT") :]

    result = result.replace("DEFAULT (CURRENT_TIMESTAMP)", "DEFAULT CURRENT_TIMESTAMP")
    result = result.replace("DEFAULT (CURRENT_DATE)", "DEFAULT CURRENT_DATE")
    return re.sub(r"\s+", " ", result).strip()


def postgres_table_constraint(
    table_name: str,
    constraint: str,
    table_columns=None,
) -> str:
    """Translate date/time checks that relied on SQLite coercion functions."""

    result = str(constraint)
    if table_columns is None:
        table_columns = SCHEMA_DINH_NGHIA[table_name]["columns"]
    date_columns = {
        name for name in table_columns if name.startswith("ngay_")
    }
    timestamp_columns = {
        name
        for name in table_columns
        if name in _SYSTEM_TIMESTAMP_COLUMNS
        or (table_name, name) in _BUSINESS_TIMESTAMP_COLUMNS
    }
    for column_name in sorted(date_columns | timestamp_columns, key=len, reverse=True):
        escaped = re.escape(column_name)
        result = re.sub(
            rf"NULLIF\(\s*{escaped}\s*,\s*''\s*\)",
            column_name,
            result,
            flags=re.IGNORECASE,
        )
        result = re.sub(
            rf"COALESCE\(\s*trim\(\s*{escaped}\s*\)\s*,\s*''\s*\)\s*=\s*''",
            f"{column_name} IS NULL",
            result,
            flags=re.IGNORECASE,
        )
        result = re.sub(
            rf"COALESCE\(\s*trim\(\s*{escaped}\s*\)\s*,\s*''\s*\)\s*!=\s*''",
            f"{column_name} IS NOT NULL",
            result,
            flags=re.IGNORECASE,
        )
        result = re.sub(
            rf"(?:date|datetime)\(\s*{escaped}\s*\)",
            column_name,
            result,
            flags=re.IGNORECASE,
        )
    return result


def build_create_table_sql(table_name: str, table_spec: dict) -> str:
    columns = []
    primary_keys = tuple(table_spec.get("primary_keys", ()))
    for column_name, sqlite_definition in table_spec["columns"].items():
        definition = postgres_column_definition(
            table_name, column_name, sqlite_definition
        )
        if primary_keys and column_name in primary_keys:
            definition = re.sub(r"\bPRIMARY KEY\b", "", definition).strip()
        columns.append(f"{column_name} {definition}")
    if primary_keys:
        columns.append(f"PRIMARY KEY ({', '.join(primary_keys)})")
    columns.extend(
        postgres_table_constraint(
            table_name,
            constraint,
            table_spec["columns"],
        )
        for constraint in table_spec.get("unique_constraints", ())
    )
    columns.extend(
        postgres_table_constraint(
            table_name,
            constraint,
            table_spec["columns"],
        )
        for constraint in table_spec.get("foreign_keys", ())
        if not constraint.lstrip().upper().startswith("FOREIGN KEY")
    )
    return f"CREATE TABLE {table_name} ({', '.join(columns)})"


def _foreign_key_name(table_name: str, index: int, definition: str) -> str:
    digest = sha256(definition.encode("utf-8")).hexdigest()[:8]
    return f"fk_{table_name}_{index}_{digest}"[:63]


def _create_foreign_keys(
    cursor,
    table_names=None,
    *,
    if_not_exists=False,
) -> None:
    selected_tables = (
        tuple(SCHEMA_DINH_NGHIA)
        if table_names is None
        else tuple(table_names)
    )
    for table_name in selected_tables:
        table_spec = HISTORICAL_SCHEMA_DINH_NGHIA[table_name]
        foreign_keys = [
            constraint
            for constraint in table_spec.get("foreign_keys", ())
            if constraint.lstrip().upper().startswith("FOREIGN KEY")
        ]
        for index, definition in enumerate(foreign_keys, 1):
            name = _foreign_key_name(table_name, index, definition)
            if if_not_exists:
                cursor.execute(
                    f"""DO $$
                        BEGIN
                          IF NOT EXISTS (
                              SELECT 1 FROM pg_constraint
                              WHERE conrelid = '{table_name}'::regclass
                                AND conname = '{name}'
                          ) THEN
                            ALTER TABLE {table_name}
                                ADD CONSTRAINT {name} {definition};
                          END IF;
                        END $$"""
                )
            else:
                cursor.execute(
                    f"ALTER TABLE {table_name} ADD CONSTRAINT {name} {definition}"
                )


def _create_extensions(cursor) -> None:
    cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    cursor.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_unaccent(value TEXT)
           RETURNS TEXT LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS $$
             SELECT public.unaccent('public.unaccent', value)
           $$"""
    )


def _create_search_indexes(cursor) -> None:
    specs = {
        "ke_hoach_lcnt": ("ma_ke_hoach", "ten_ke_hoach", "ten_du_an_du_toan"),
        "goi_thau": ("ma_goi_thau", "ten_goi_thau"),
        "chu_dau_tu": ("ma_chu_dau_tu", "ten_chu_dau_tu", "ten_viet_tat", "ma_so_thue"),
        "nha_thau": ("ma_nha_thau", "ten_nha_thau", "ten_viet_tat", "ma_so_thue"),
        "chuyen_gia": ("ho_ten", "so_cccd", "so_chung_chi"),
        "hop_dong": ("so_hop_dong", "ten_hop_dong"),
    }
    for table_name, columns in specs.items():
        expression = " || ' ' || ".join(
            f"COALESCE({column}, '')" for column in columns
        )
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_search_trgm "
            f"ON {table_name} USING GIN ((bf_unaccent(lower({expression}))) gin_trgm_ops)"
        )


def _create_indexes(cursor) -> None:
    versioned_tables = (
        "chu_dau_tu",
        "ke_hoach_lcnt",
        "goi_thau",
        "nha_thau",
        "chuyen_gia",
        "hop_dong",
    )
    synced_tables = versioned_tables + (
        "phan_cong_nhan_su",
        "danh_muc_trang_thai_hop_dong",
        "thong_tin_mo_thau",
        "goi_thau_hang_hoa",
        "hang_hoa_du_thau_nha_thau",
        "ma_tran_phan_quyen",
    )
    owner_tables = tuple(
        table_name
        for table_name, table_spec in SCHEMA_DINH_NGHIA.items()
        if "owner_type" in table_spec.get("columns", {})
    )
    for table_name in versioned_tables:
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_owner_updated "
            f"ON {table_name} (organization_id, updated_at, id)"
        )
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_owner_latest "
            f"ON {table_name} (organization_id, is_latest, archived_at, id)"
        )
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_owner_root "
            f"ON {table_name} (organization_id, id_goc)"
        )
    for table_name in synced_tables:
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_owner_sync_version "
            f"ON {table_name} (organization_id, sync_version, id)"
        )
    for table_name in owner_tables:
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_owner_type_owner "
            f"ON {table_name} (owner_type, organization_id)"
        )

    for table_name, date_column in (
        ("ke_hoach_lcnt", "ngay_phe_duyet"),
        ("goi_thau", "ngay_quyet_dinh"),
        ("hop_dong", "ngay_ky"),
    ):
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_latest_date "
            f"ON {table_name} (organization_id, {date_column}, id) "
            "WHERE is_latest = 1 AND archived_at IS NULL"
        )

    for table_name in (
        "chu_dau_tu",
        "ke_hoach_lcnt",
        "nha_thau",
        "chuyen_gia",
        "hop_dong",
    ):
        cursor.execute(
            f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{table_name}_unique_version "
            f"ON {table_name} (organization_id, COALESCE(NULLIF(id_goc, ''), id), phien_ban)"
        )
        cursor.execute(
            f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{table_name}_unique_latest "
            f"ON {table_name} (organization_id, COALESCE(NULLIF(id_goc, ''), id)) "
            "WHERE is_latest = 1"
        )
    for table_name, sort_column in (
        ("chu_dau_tu", "ten_chu_dau_tu"),
        ("ke_hoach_lcnt", "ma_ke_hoach"),
        ("goi_thau", "ma_goi_thau"),
        ("nha_thau", "ten_nha_thau"),
        ("chuyen_gia", "ho_ten"),
        ("hop_dong", "ten_hop_dong"),
    ):
        cursor.execute(
            f"CREATE INDEX IF NOT EXISTS idx_{table_name}_default_page "
            f"ON {table_name} (organization_id, (COALESCE({sort_column}, '')), id) "
            "WHERE is_latest = 1 AND archived_at IS NULL"
        )
    cursor.execute(
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_unique_plan_snapshot_version
           ON goi_thau (
               organization_id, COALESCE(NULLIF(id_goc, ''), id),
               phien_ban, ke_hoach_id
           )"""
    )
    cursor.execute(
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_unique_latest
           ON goi_thau (
               organization_id, COALESCE(NULLIF(id_goc, ''), id),
               COALESCE(ke_hoach_id, '')
           ) WHERE is_latest = 1"""
    )

    for table_name, column_name in (
        ("chu_dau_tu", "ma_chu_dau_tu"),
        ("chu_dau_tu", "ma_so_thue"),
        ("ke_hoach_lcnt", "ma_ke_hoach"),
        ("nha_thau", "ma_nha_thau"),
        ("nha_thau", "ma_so_thue"),
        ("chuyen_gia", "so_cccd"),
        ("hop_dong", "so_hop_dong"),
    ):
        cursor.execute(
            f"CREATE UNIQUE INDEX IF NOT EXISTS idx_{table_name}_{column_name}_owner_latest_unique "
            f"ON {table_name} (organization_id, lower(trim({column_name}))) "
            f"WHERE is_latest = 1 AND {column_name} IS NOT NULL "
            f"AND trim({column_name}) <> ''"
        )
    cursor.execute(
        """CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_ma_goi_thau_owner_plan_latest_unique
           ON goi_thau (
               organization_id, COALESCE(ke_hoach_id, ''), lower(trim(ma_goi_thau))
           ) WHERE is_latest = 1 AND ma_goi_thau IS NOT NULL
             AND trim(ma_goi_thau) <> ''"""
    )

    statements = (
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_ke_hoach ON goi_thau (organization_id, ke_hoach_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_nha_thau_trung ON goi_thau (organization_id, nha_thau_trung_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_package_documents_package ON tai_lieu_goi_thau (organization_id, goi_thau_id, evaluation_batch_id, document_type)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_package_documents_general_type ON tai_lieu_goi_thau (organization_id, goi_thau_id, document_type) WHERE evaluation_batch_id IS NULL",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_package_documents_batch_type ON tai_lieu_goi_thau (organization_id, goi_thau_id, evaluation_batch_id, document_type) WHERE evaluation_batch_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_package_documents_uploader ON tai_lieu_goi_thau (uploaded_by_id, uploaded_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_package_documents_batch_fk ON tai_lieu_goi_thau (organization_id, evaluation_batch_id) WHERE evaluation_batch_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_ke_hoach_cong_viec_parent ON ke_hoach_cong_viec (organization_id, ke_hoach_id, loai, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_phan_lo_parent ON goi_thau_phan_lo (organization_id, goi_thau_id, sort_order)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_phan_lo_active_code ON goi_thau_phan_lo (organization_id, goi_thau_id, ma_phan_lo_normalized) WHERE archived_at IS NULL AND ma_phan_lo_normalized <> ''",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_hang_hoa_parent ON goi_thau_hang_hoa (organization_id, goi_thau_id, phan_lo_id, sort_order, id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_hang_hoa_lot_fk ON goi_thau_hang_hoa (organization_id, phan_lo_id) WHERE phan_lo_id IS NOT NULL",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_hang_hoa_code_no_lot ON goi_thau_hang_hoa (organization_id, goi_thau_id, lower(trim(ma_hang_hoa))) WHERE phan_lo_id IS NULL",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_goi_thau_hang_hoa_code_by_lot ON goi_thau_hang_hoa (organization_id, goi_thau_id, phan_lo_id, lower(trim(ma_hang_hoa))) WHERE phan_lo_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_bidder_goods_scope ON hang_hoa_du_thau_nha_thau (organization_id, goi_thau_id, thong_tin_mo_thau_id, phan_lo_id, sort_order, id)",
        "CREATE INDEX IF NOT EXISTS idx_bidder_goods_import_batch ON hang_hoa_du_thau_nha_thau (organization_id, import_batch_id)",
        "CREATE INDEX IF NOT EXISTS idx_bidder_goods_lot_fk ON hang_hoa_du_thau_nha_thau (organization_id, phan_lo_id) WHERE phan_lo_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_bidder_goods_requirement_fk ON hang_hoa_du_thau_nha_thau (organization_id, goi_thau_hang_hoa_id) WHERE goi_thau_hang_hoa_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_bidder_goods_manual_actor_fk ON hang_hoa_du_thau_nha_thau (uu_dai_manual_actor_id) WHERE uu_dai_manual_actor_id IS NOT NULL",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_bidder_goods_requirement ON hang_hoa_du_thau_nha_thau (organization_id, thong_tin_mo_thau_id, goi_thau_hang_hoa_id) WHERE goi_thau_hang_hoa_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_lot_batch_package ON dot_xu_ly_phan_lo (organization_id, goi_thau_id, sequence_no)",
        "CREATE INDEX IF NOT EXISTS idx_lot_batch_created_by ON dot_xu_ly_phan_lo (created_by_id)",
        "CREATE INDEX IF NOT EXISTS idx_lot_batch_detail_batch ON dot_xu_ly_phan_lo_chi_tiet (organization_id, batch_id)",
        "CREATE INDEX IF NOT EXISTS idx_lot_batch_detail_lot ON dot_xu_ly_phan_lo_chi_tiet (organization_id, lot_id)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_lot_batch_detail_one_active ON dot_xu_ly_phan_lo_chi_tiet (organization_id, lot_id) WHERE is_active = 1",
        "CREATE INDEX IF NOT EXISTS idx_lot_dependency_package ON nhom_phu_thuoc_phan_lo (organization_id, goi_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_lot_dependency_member_group ON nhom_phu_thuoc_phan_lo_thanh_vien (organization_id, dependency_group_id)",
        "CREATE INDEX IF NOT EXISTS idx_lot_dependency_member_lot ON nhom_phu_thuoc_phan_lo_thanh_vien (organization_id, lot_id)",
        "CREATE INDEX IF NOT EXISTS idx_lcnt_artifact_batch ON ho_so_nghiep_vu_lcnt (organization_id, batch_id, artifact_type, revision)",
        "CREATE INDEX IF NOT EXISTS idx_lcnt_artifact_lot ON ho_so_nghiep_vu_lcnt_phan_lo (organization_id, lot_id)",
        "CREATE INDEX IF NOT EXISTS idx_lcnt_artifact_finalized_by ON ho_so_nghiep_vu_lcnt (finalized_by_id)",
        "CREATE INDEX IF NOT EXISTS idx_lcnt_artifact_voided_by ON ho_so_nghiep_vu_lcnt (voided_by_id)",
        "CREATE INDEX IF NOT EXISTS idx_lcnt_artifact_supersedes ON ho_so_nghiep_vu_lcnt (organization_id, supersedes_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_tuy_chon_parent ON goi_thau_tuy_chon_mua_them (organization_id, goi_thau_id, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_gia_han_parent ON goi_thau_gia_han (organization_id, goi_thau_id, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_lam_ro_parent ON goi_thau_lam_ro (organization_id, goi_thau_id, loai, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_nha_thau_lien_danh_parent ON nha_thau_lien_danh_thanh_vien (organization_id, nha_thau_id, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_mo_thau_lien_danh_parent ON thong_tin_mo_thau_lien_danh_thanh_vien (organization_id, thong_tin_mo_thau_id, sort_order)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_nha_thau_lien_danh_one_leader ON nha_thau_lien_danh_thanh_vien (organization_id, nha_thau_id) WHERE vai_tro = 'Đứng đầu liên danh'",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_mo_thau_lien_danh_one_leader ON thong_tin_mo_thau_lien_danh_thanh_vien (organization_id, thong_tin_mo_thau_id) WHERE vai_tro = 'Đứng đầu liên danh'",
        "CREATE INDEX IF NOT EXISTS idx_nha_thau_tham_du_mo_thau_bid ON nha_thau_tham_du_mo_thau (organization_id, thong_tin_mo_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_vong_danh_gia_package ON vong_danh_gia (organization_id, goi_thau_id, thu_tu)",
        "CREATE INDEX IF NOT EXISTS idx_tieu_chi_danh_gia_round ON tieu_chi_danh_gia (organization_id, vong_danh_gia_id, thu_tu)",
        "CREATE INDEX IF NOT EXISTS idx_tieu_chi_danh_gia_parent ON tieu_chi_danh_gia (organization_id, tieu_chi_cha_id)",
        "CREATE INDEX IF NOT EXISTS idx_detailed_evaluation_report_round ON bao_cao_danh_gia_nha_thau (organization_id, vong_danh_gia_id)",
        "CREATE INDEX IF NOT EXISTS idx_detailed_evaluation_report_opening ON bao_cao_danh_gia_nha_thau (organization_id, thong_tin_mo_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_detailed_evaluation_row_report ON chi_tiet_danh_gia_nha_thau (organization_id, bao_cao_danh_gia_nha_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_detailed_evaluation_row_criterion ON chi_tiet_danh_gia_nha_thau (organization_id, tieu_chi_danh_gia_id)",
        "CREATE INDEX IF NOT EXISTS idx_ket_qua_danh_gia_opening ON ket_qua_danh_gia_nha_thau (organization_id, thong_tin_mo_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_ke_hoach ON hop_dong (organization_id, ke_hoach_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_chu_dau_tu ON hop_dong (organization_id, chu_dau_tu_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_nha_thau ON hop_dong (organization_id, nha_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_goi_thau_owner_hd ON hop_dong_goi_thau (organization_id, hop_dong_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_goi_thau_owner_gt ON hop_dong_goi_thau (organization_id, goi_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_chuyen_gia_owner_gt ON goi_thau_chuyen_gia (organization_id, goi_thau_id, loai)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_chuyen_gia_owner_cg ON goi_thau_chuyen_gia (organization_id, chuyen_gia_id)",
        "CREATE INDEX IF NOT EXISTS idx_thong_tin_mo_thau_goi_thau ON thong_tin_mo_thau (organization_id, goi_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_thong_tin_mo_thau_nha_thau ON thong_tin_mo_thau (organization_id, nha_thau_id)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_thong_tin_mo_thau_active_business_key ON thong_tin_mo_thau (organization_id, goi_thau_id, nha_thau_id, ma_phan_lo_normalized) WHERE archived_at IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_phan_cong_owner_target ON phan_cong_nhan_su (organization_id, id_muc_tieu, loai_doi_tuong, id_nhan_vien)",
        "CREATE INDEX IF NOT EXISTS idx_phan_cong_owner_assignee ON phan_cong_nhan_su (organization_id, id_nhan_vien, loai_doi_tuong, id_muc_tieu)",
        "CREATE INDEX IF NOT EXISTS idx_activity_target_timeline ON nhat_ky_thuc_hien (organization_id, target_type, target_root_id, occurred_at DESC, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_activity_actor_timeline ON nhat_ky_thuc_hien (organization_id, actor_user_id, occurred_at DESC)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_activity_mutation_dedupe ON nhat_ky_thuc_hien (organization_id, actor_user_id, client_mutation_id, action, target_id, COALESCE(related_document_id, ''), COALESCE(related_assignment_id, '')) WHERE client_mutation_id IS NOT NULL AND client_mutation_id <> ''",
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_active ON auth_sessions (user_id, revoked_at, absolute_expires_at)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_sessions_one_active_per_user ON auth_sessions (user_id) WHERE revoked_at IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_expiry ON auth_sessions (idle_expires_at, absolute_expires_at, revoked_at)",
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_active_idle_expiry ON auth_sessions (idle_expires_at) WHERE revoked_at IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_active_absolute_expiry ON auth_sessions (absolute_expires_at) WHERE revoked_at IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_revoked_cleanup ON auth_sessions (revoked_at) WHERE revoked_at IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_dinh_danh_ngoai_user ON dinh_danh_ngoai (user_id)",
        "CREATE INDEX IF NOT EXISTS idx_password_reset_user_active ON password_reset_tokens (user_id, used_at, expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_password_reset_expires ON password_reset_tokens (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_email_delivery_user_purpose ON email_delivery_status (user_id, purpose, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_email_delivery_retry ON email_delivery_status (status, next_attempt_at)",
        "CREATE INDEX IF NOT EXISTS idx_email_delivery_stale ON email_delivery_status (locked_at) WHERE status = 'sending'",
        "CREATE INDEX IF NOT EXISTS idx_user_notifications_user_created ON user_notifications (user_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_user_notifications_user_unread ON user_notifications (user_id, created_at DESC) WHERE read_at IS NULL",
        "CREATE INDEX IF NOT EXISTS idx_rate_limit_expires ON rate_limit_buckets (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_workspace_updated ON ai_conversations (user_id, organization_id, updated_at DESC) WHERE status = 'active'",
        "CREATE INDEX IF NOT EXISTS idx_ai_conversations_workspace_created ON ai_conversations (organization_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation_created ON ai_messages (organization_id, conversation_id, created_at ASC)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_messages_client_request ON ai_messages (organization_id, conversation_id, client_request_id) WHERE client_request_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_ai_tool_executions_conversation_created ON ai_tool_executions (organization_id, conversation_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_tool_executions_message ON ai_tool_executions (organization_id, message_id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_tool_executions_user ON ai_tool_executions (user_id, organization_id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_feedback_user ON ai_feedback (user_id, organization_id)",
        "CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_workspace_date ON ai_usage_daily (organization_id, usage_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_usage_daily_user ON ai_usage_daily (user_id, organization_id, usage_date DESC)",
        "CREATE INDEX IF NOT EXISTS idx_ai_knowledge_active_org ON ai_knowledge_documents (organization_id, document_type, updated_at DESC) WHERE status = 'active'",
        "CREATE INDEX IF NOT EXISTS idx_ai_knowledge_approved_by ON ai_knowledge_documents (approved_by)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_knowledge_scope_hash ON ai_knowledge_documents (COALESCE(organization_id, ''), content_hash)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_knowledge_one_global_active ON ai_knowledge_documents (document_type, document_number) WHERE organization_id IS NULL AND status = 'active'",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_knowledge_one_org_active ON ai_knowledge_documents (organization_id, document_type, document_number) WHERE organization_id IS NOT NULL AND status = 'active'",
        "CREATE INDEX IF NOT EXISTS idx_ai_knowledge_chunks_document ON ai_knowledge_chunks (document_id, chunk_index)",
        "CREATE INDEX IF NOT EXISTS idx_partner_lookup_cache_expiry ON partner_lookup_cache (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_partner_upstream_open ON partner_upstream_health (opened_until, probe_locked_until)",
        "CREATE INDEX IF NOT EXISTS idx_partner_enrichment_claim ON partner_enrichment_jobs (status, available_at, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_partner_enrichment_stale ON partner_enrichment_jobs (locked_at) WHERE status = 'processing'",
        "CREATE INDEX IF NOT EXISTS idx_partner_enrichment_terminal_cleanup ON partner_enrichment_jobs (updated_at) WHERE status IN ('completed', 'failed')",
        "CREATE INDEX IF NOT EXISTS idx_websocket_leases_expiry ON websocket_connection_leases (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_websocket_leases_user ON websocket_connection_leases (user_id, expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_websocket_leases_ip ON websocket_connection_leases (client_ip_hash, expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_document_jobs_claim ON document_jobs (status, available_at, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_document_jobs_stale ON document_jobs (locked_at) WHERE status = 'processing'",
        "CREATE INDEX IF NOT EXISTS idx_document_jobs_expiry ON document_jobs (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_document_jobs_record_owner ON document_jobs (organization_id, record_type, record_id, user_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_thanh_vien_to_chuc_to_chuc ON thanh_vien_to_chuc (organization_id, user_id)",
        "CREATE INDEX IF NOT EXISTS idx_organization_subscriptions_status_expiry ON organization_subscriptions (status, expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_account_subscriptions_status_expiry ON account_subscriptions (status, expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_api_idempotency_created ON api_idempotency (created_at)",
        "CREATE INDEX IF NOT EXISTS idx_deleted_records_owner_deleted ON deleted_records (organization_id, deleted_at)",
        "CREATE INDEX IF NOT EXISTS idx_deleted_records_retention_cutoff ON deleted_records (deleted_at, organization_id, delete_version)",
        "CREATE INDEX IF NOT EXISTS idx_deleted_records_owner_delete_version ON deleted_records (organization_id, delete_version)",
        "CREATE INDEX IF NOT EXISTS idx_deleted_records_owner_table ON deleted_records (organization_id, table_name)",
        "CREATE INDEX IF NOT EXISTS idx_sync_mutations_owner_created ON sync_mutations (organization_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_sync_mutations_retention_cutoff ON sync_mutations (created_at)",
        "CREATE INDEX IF NOT EXISTS idx_sync_mutations_actor ON sync_mutations (actor_user_id)",
        "CREATE INDEX IF NOT EXISTS idx_audit_log_owner_created ON audit_log (organization_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_log_actor_created ON audit_log (actor_user_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_log_action_created ON audit_log (action, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_record_edit_ownership_user ON record_edit_ownership (organization_id, user_id, table_name)",
        "CREATE INDEX IF NOT EXISTS idx_record_edit_ownership_by_user ON record_edit_ownership (user_id)",
        "CREATE INDEX IF NOT EXISTS idx_account_subscriptions_package ON account_subscriptions (package_id)",
        "CREATE INDEX IF NOT EXISTS idx_organization_subscriptions_package ON organization_subscriptions (package_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_rebid_parent ON goi_thau (organization_id, rebid_from_package_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_phan_lo_winner ON goi_thau_phan_lo (organization_id, nha_thau_trung_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_chu_dau_tu_thanh_ly ON hop_dong (organization_id, chu_dau_tu_thanh_ly_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_nha_thau_thanh_ly ON hop_dong (organization_id, nha_thau_thanh_ly_id)",
        "CREATE INDEX IF NOT EXISTS idx_hop_dong_trang_thai ON hop_dong (organization_id, trang_thai_hop_dong)",
        "CREATE INDEX IF NOT EXISTS idx_ke_hoach_chu_dau_tu ON ke_hoach_lcnt (organization_id, chu_dau_tu_id)",
        "CREATE INDEX IF NOT EXISTS idx_ket_qua_goi_thau ON ket_qua_danh_gia_nha_thau (organization_id, goi_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_ket_qua_goi_thau_opening ON ket_qua_danh_gia_nha_thau (organization_id, goi_thau_id, thong_tin_mo_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_nha_thau_lien_danh_member ON nha_thau_lien_danh_thanh_vien (organization_id, thanh_vien_nha_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_nha_thau_tham_du_root ON nha_thau_tham_du_mo_thau (organization_id, nha_thau_goc_id)",
        "CREATE INDEX IF NOT EXISTS idx_nha_thau_tham_du_version ON nha_thau_tham_du_mo_thau (organization_id, nha_thau_phien_ban_id)",
        "CREATE INDEX IF NOT EXISTS idx_phan_cong_nhan_su_employee ON phan_cong_nhan_su (id_nhan_vien)",
        "CREATE INDEX IF NOT EXISTS idx_mo_thau_lien_danh_member ON thong_tin_mo_thau_lien_danh_thanh_vien (organization_id, thanh_vien_nha_thau_id)",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_cache_expiry ON contractor_violation_cache (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_target ON contractor_violation_checks (organization_id, bid_opening_record_id, joint_venture_member_id, checked_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_package ON contractor_violation_checks (organization_id, package_id, bid_closing_at)",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_lot ON contractor_violation_checks (organization_id, lot_id) WHERE lot_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_contractor ON contractor_violation_checks (organization_id, contractor_id, checked_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_member ON contractor_violation_checks (organization_id, joint_venture_member_id, checked_at DESC) WHERE joint_venture_member_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_contractor_violation_check_creator ON contractor_violation_checks (created_by)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_moc_tien_do_package ON goi_thau_moc_tien_do (organization_id, goi_thau_id, sort_order, ma_moc)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_moc_tien_do_status ON goi_thau_moc_tien_do (organization_id, trang_thai, ngay_du_kien)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_dieu_chinh_hsmt_package ON goi_thau_dieu_chinh_hsmt (organization_id, goi_thau_id, sequence)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_dieu_chinh_hsmt_created_by ON goi_thau_dieu_chinh_hsmt (created_by_id)",
        "CREATE INDEX IF NOT EXISTS idx_goi_thau_dieu_chinh_hsmt_updated_by ON goi_thau_dieu_chinh_hsmt (updated_by_id)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_revision_family ON procurement_source_revision (organization_id, provider, family_key, entity_kind, revision_no)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_revision_local_root ON procurement_source_revision (organization_id, local_root_id) WHERE local_root_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_procurement_revision_operation ON procurement_source_revision (organization_id, operation_id) WHERE operation_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_procurement_binding_family ON procurement_source_binding (organization_id, provider, family_key, symbol, notify_no)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_binding_local_root ON procurement_source_binding (organization_id, local_root_id)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_operation_status ON procurement_import_operation (organization_id, status, updated_at)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_session_owner ON procurement_import_session (organization_id, user_id, workspace_lease)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_session_family ON procurement_import_session (organization_id, family_key, status)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_session_expiry ON procurement_import_session (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_raw_entity ON procurement_raw_snapshot (organization_id, provider, entity_kind, canonical_code, retrieved_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_procurement_raw_content ON procurement_raw_snapshot (organization_id, content_hash)",
        "CREATE INDEX IF NOT EXISTS idx_conflict_drafts_actor_workspace ON conflict_resolution_drafts (organization_id, actor_user_id, workspace_fingerprint, status, updated_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_conflict_drafts_expiry ON conflict_resolution_drafts (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_catalog ON word_template (organization_id, retired_at, updated_at DESC, id)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_version_history ON word_template_version (organization_id, template_id, version_no DESC)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_version_checksum ON word_template_version (organization_id, sha256)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_preflight_history ON word_template_preflight_run (organization_id, template_version_id, run_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_publication_history ON word_template_publication_event (organization_id, template_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_projection_claim ON word_template_projection_outbox (status, available_at, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_word_template_projection_template ON word_template_projection_outbox (organization_id, template_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_word_assignment_template ON word_publication_assignment_v2 (organization_id, template_id, document_type, context_key, sort_order)",
        "CREATE INDEX IF NOT EXISTS idx_word_assignment_config_revision ON word_template_assignment_config (organization_id, revision)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_word_assignment_projection_digest ON word_template_projection_outbox (organization_id, event_type, desired_checksum) WHERE event_type = 'ASSIGNMENT'",
        "CREATE INDEX IF NOT EXISTS idx_legal_instrument_version_effective ON legal_instrument_version (effective_from, effective_to, instrument_id)",
        "CREATE INDEX IF NOT EXISTS idx_legal_profile_version_effective ON legal_source_profile_version (effective_from, effective_to, priority DESC, profile_id)",
        "CREATE INDEX IF NOT EXISTS idx_plan_legal_binding_history ON plan_legal_binding (organization_id, plan_id, binding_revision DESC)",
        "CREATE INDEX IF NOT EXISTS idx_package_legal_binding_history ON package_legal_binding (organization_id, package_id, binding_revision DESC)",
        "CREATE INDEX IF NOT EXISTS idx_generated_document_template ON generated_document_provenance (organization_id, template_version_id, created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_generated_document_record ON generated_document_provenance (organization_id, record_type, record_id, created_at DESC) WHERE record_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_pending_email_changes_expiry ON pending_email_changes (expires_at)",
        "CREATE INDEX IF NOT EXISTS idx_document_export_capabilities_user ON document_export_capabilities (user_id, organization_id)",
        "CREATE INDEX IF NOT EXISTS idx_sensitive_record_read_capabilities_user ON sensitive_record_read_capabilities (user_id, organization_id)",
        "CREATE INDEX IF NOT EXISTS idx_assignment_history_member ON phan_cong_nhan_su_lich_su (organization_id, id_nhan_vien, ended_at)",
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_deleted_records_unique_record ON deleted_records (organization_id, table_name, record_id)",
        *REQUIRED_POST_V64_FK_INDEXES,
    )
    for statement in statements:
        if any(table_name in statement for table_name in RETIRED_PROCUREMENT_CENTER_TABLES):
            continue
        cursor.execute(statement)
    _create_search_indexes(cursor)


def _create_synced_delete_trigger_function(cursor) -> None:
    """Install the tombstone trigger function without rebuilding other DDL."""

    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_log_synced_delete()
           RETURNS trigger LANGUAGE plpgsql AS $$
           DECLARE next_version BIGINT;
           BEGIN
             IF OLD.organization_id IS NULL OR OLD.organization_id = '' THEN
               RETURN OLD;
             END IF;
             INSERT INTO sync_metadata (organization_id, current_version)
             VALUES (OLD.organization_id, 0)
             ON CONFLICT (organization_id) DO NOTHING;
             UPDATE sync_metadata
             SET current_version = current_version + 1,
                 updated_at = CURRENT_TIMESTAMP
             WHERE organization_id = OLD.organization_id
             RETURNING current_version INTO next_version;
             INSERT INTO deleted_records (
               table_name, record_id, organization_id, deleted_at,
               delete_version, record_snapshot_json
             ) VALUES (
               TG_TABLE_NAME, OLD.id, OLD.organization_id, CURRENT_TIMESTAMP,
               next_version, to_jsonb(OLD)::text
             )
             ON CONFLICT (organization_id, table_name, record_id) DO UPDATE SET
               deleted_at = EXCLUDED.deleted_at,
               record_snapshot_json = EXCLUDED.record_snapshot_json,
               delete_version = GREATEST(
                 COALESCE(deleted_records.delete_version, 0),
                 COALESCE(EXCLUDED.delete_version, 0)
               );
             RETURN OLD;
           END $$"""
    )


def _create_trigger_functions(cursor) -> None:
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_validate_workspace_owner()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NEW.owner_type = 'organization' AND NOT EXISTS (
               SELECT 1 FROM to_chuc
               WHERE id = NEW.organization_id
                 AND COALESCE(
                       to_jsonb(to_chuc)->>'trang_thai', 'active'
                     ) = 'active'
             ) THEN
               RAISE EXCEPTION 'organization workspace does not exist'
                 USING ERRCODE = '23514';
             ELSIF NEW.owner_type = 'personal' AND NOT EXISTS (
               SELECT 1 FROM tai_khoan
               WHERE id = substring(NEW.organization_id FROM 10)
                 AND vai_tro <> 'super_admin'
                 AND COALESCE(
                       to_jsonb(tai_khoan)->>'trang_thai', 'active'
                     ) = 'active'
             ) THEN
               RAISE EXCEPTION 'personal workspace owner does not exist'
                 USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_set_lineage()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF TG_OP = 'INSERT' AND (NEW.id_goc IS NULL OR btrim(NEW.id_goc) = '') THEN
               NEW.id_goc := NEW.id;
             ELSIF TG_OP = 'UPDATE'
               AND OLD.id_goc IS NOT NULL AND btrim(OLD.id_goc) <> ''
               AND NEW.id_goc IS DISTINCT FROM OLD.id_goc THEN
               RAISE EXCEPTION 'LINEAGE_IMMUTABLE' USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_touch_synced_row()
           RETURNS trigger LANGUAGE plpgsql AS $$
           DECLARE next_version BIGINT;
           BEGIN
             IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
                AND COALESCE(NEW.sync_version, 0) = COALESCE(OLD.sync_version, 0)
                AND NEW.organization_id IS NOT NULL AND NEW.organization_id <> '' THEN
               INSERT INTO sync_metadata (organization_id, current_version)
               VALUES (NEW.organization_id, 0)
               ON CONFLICT (organization_id) DO NOTHING;
               UPDATE sync_metadata
               SET current_version = current_version + 1,
                   updated_at = CURRENT_TIMESTAMP
               WHERE organization_id = NEW.organization_id
               RETURNING current_version INTO next_version;
               NEW.sync_version := next_version;
               NEW.updated_at := CURRENT_TIMESTAMP;
             END IF;
             RETURN NEW;
           END $$"""
    )
    _create_synced_delete_trigger_function(cursor)
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_validate_record_edit_owner()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NOT EXISTS (
                  SELECT 1 FROM to_chuc
                  WHERE id = NEW.organization_id
                    AND COALESCE(
                          to_jsonb(to_chuc)->>'trang_thai', 'active'
                        ) = 'active'
                )
                AND NOT (
                  NEW.organization_id = 'personal:' || NEW.user_id
                  AND EXISTS (
                    SELECT 1 FROM tai_khoan
                    WHERE id = NEW.user_id AND vai_tro <> 'super_admin'
                      AND COALESCE(
                            to_jsonb(tai_khoan)->>'trang_thai', 'active'
                          ) = 'active'
                  )
                ) THEN
               RAISE EXCEPTION 'record ownership workspace does not exist'
                 USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_validate_verified_email_change()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF OLD.email_norm IS DISTINCT FROM NEW.email_norm AND NOT EXISTS (
               SELECT 1 FROM pending_email_changes pending
               WHERE pending.user_id = OLD.id
                 AND pending.current_email_norm = OLD.email_norm
                 AND pending.pending_email_norm = NEW.email_norm
                 AND pending.pending_email = NEW.email
                 AND pending.verified_at IS NOT NULL
                 AND pending.verified_at <= pending.expires_at
                 AND extract(epoch FROM CURRENT_TIMESTAMP)::BIGINT < pending.expires_at
             ) THEN
               RAISE EXCEPTION 'verified email change required'
                 USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_validate_assignment_target()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NEW.loai_doi_tuong NOT IN ('kehoach', 'goithau', 'hopdong')
                OR (NEW.loai_doi_tuong = 'kehoach' AND NOT EXISTS (
                  SELECT 1 FROM ke_hoach_lcnt WHERE organization_id = NEW.organization_id AND id = NEW.id_muc_tieu
                ))
                OR (NEW.loai_doi_tuong = 'goithau' AND NOT EXISTS (
                  SELECT 1 FROM goi_thau WHERE organization_id = NEW.organization_id AND id = NEW.id_muc_tieu
                ))
                OR (NEW.loai_doi_tuong = 'hopdong' AND NOT EXISTS (
                  SELECT 1 FROM hop_dong WHERE organization_id = NEW.organization_id AND id = NEW.id_muc_tieu
                )) THEN
               RAISE EXCEPTION 'ASSIGNMENT_TENANT_MISMATCH' USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_validate_contract_package()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NOT EXISTS (
               SELECT 1
               FROM hop_dong hd
               JOIN ke_hoach_lcnt hdkh
                 ON hdkh.organization_id = hd.organization_id AND hdkh.id = hd.ke_hoach_id
               JOIN goi_thau gt
                 ON gt.organization_id = NEW.organization_id AND gt.id = NEW.goi_thau_id
               JOIN ke_hoach_lcnt gtkh
                 ON gtkh.organization_id = gt.organization_id AND gtkh.id = gt.ke_hoach_id
               WHERE hd.organization_id = NEW.organization_id
                 AND hd.id = NEW.hop_dong_id
                 AND hd.archived_at IS NULL AND gt.archived_at IS NULL
                 AND COALESCE(NULLIF(hdkh.id_goc, ''), hdkh.id)
                   = COALESCE(NULLIF(gtkh.id_goc, ''), gtkh.id)
             ) THEN
               RAISE EXCEPTION 'CONTRACT_PACKAGE_BUSINESS_MISMATCH' USING ERRCODE = '23514';
             END IF;
             RETURN NEW;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_forbid_audit_mutation()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             RAISE EXCEPTION 'AUDIT_LOG_IMMUTABLE' USING ERRCODE = '23514';
           END $$"""
    )


def _create_contractor_violation_stale_function(cursor) -> None:
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_mark_contractor_violation_package_stale(
               p_workspace_id TEXT, p_package_id TEXT
           ) RETURNS void LANGUAGE plpgsql AS $$
           BEGIN
             UPDATE contractor_violation_checks
                SET is_stale = 1, updated_at = CURRENT_TIMESTAMP
              WHERE organization_id = p_workspace_id
                AND package_id = p_package_id AND is_stale = 0;
             UPDATE thong_tin_mo_thau
                SET violation_status = 'NOT_CHECKED',
                    violation_bid_closing_at = NULL,
                    violation_checked_at = NULL
              WHERE organization_id = p_workspace_id
                AND goi_thau_id = p_package_id;
             UPDATE thong_tin_mo_thau_lien_danh_thanh_vien AS member
                SET violation_status = 'NOT_CHECKED',
                    violation_bid_closing_at = NULL,
                    violation_checked_at = NULL
               FROM thong_tin_mo_thau AS opening
              WHERE opening.organization_id = p_workspace_id
                AND opening.goi_thau_id = p_package_id
                AND member.organization_id = opening.organization_id
                AND member.thong_tin_mo_thau_id = opening.id;
           END $$"""
    )
    cursor.execute(
        """CREATE OR REPLACE FUNCTION bf_mark_contractor_violation_checks_stale()
           RETURNS trigger LANGUAGE plpgsql AS $$
           BEGIN
             IF NEW.thoi_gian_dong_thau IS NOT DISTINCT FROM OLD.thoi_gian_dong_thau THEN
               RETURN NEW;
             END IF;
             PERFORM bf_mark_contractor_violation_package_stale(
               NEW.organization_id, NEW.id
             );
             RETURN NEW;
           END $$"""
    )


def _create_triggers(cursor) -> None:
    _create_trigger_functions(cursor)
    _create_contractor_violation_stale_function(cursor)
    owner_tables = tuple(
        table_name
        for table_name, table_spec in SCHEMA_DINH_NGHIA.items()
        if "owner_type" in table_spec.get("columns", {})
    )
    for table_name in owner_tables:
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_workspace_owner "
            f"ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_workspace_owner "
            f"BEFORE INSERT OR UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION bf_validate_workspace_owner()"
        )
    for table_name in (
        "chu_dau_tu",
        "ke_hoach_lcnt",
        "goi_thau",
        "nha_thau",
        "chuyen_gia",
        "hop_dong",
    ):
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_lineage ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_lineage "
            f"BEFORE INSERT OR UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION bf_set_lineage()"
        )
    for table_name in (
        "chu_dau_tu",
        "ke_hoach_lcnt",
        "goi_thau",
        "nha_thau",
        "chuyen_gia",
        "hop_dong",
        "phan_cong_nhan_su",
        "danh_muc_trang_thai_hop_dong",
        "thong_tin_mo_thau",
        "goi_thau_hang_hoa",
        "hang_hoa_du_thau_nha_thau",
        "ma_tran_phan_quyen",
    ):
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_updated_at ON {table_name}"
        )
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_deleted_log ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_updated_at "
            f"BEFORE UPDATE ON {table_name} FOR EACH ROW "
            "EXECUTE FUNCTION bf_touch_synced_row()"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_deleted_log "
            f"AFTER DELETE ON {table_name} FOR EACH ROW "
            "EXECUTE FUNCTION bf_log_synced_delete()"
        )
    cursor.execute(
        """DROP TRIGGER IF EXISTS trg_record_edit_ownership_workspace
           ON record_edit_ownership"""
    )
    cursor.execute(
        """CREATE TRIGGER trg_record_edit_ownership_workspace
           BEFORE INSERT OR UPDATE ON record_edit_ownership
           FOR EACH ROW EXECUTE FUNCTION bf_validate_record_edit_owner()"""
    )
    cursor.execute(
        """DROP TRIGGER IF EXISTS trg_tai_khoan_verified_email_update
           ON tai_khoan"""
    )
    cursor.execute(
        """CREATE TRIGGER trg_tai_khoan_verified_email_update
           BEFORE UPDATE OF email, email_norm ON tai_khoan
           FOR EACH ROW EXECUTE FUNCTION bf_validate_verified_email_change()"""
    )
    cursor.execute(
        """DROP TRIGGER IF EXISTS trg_phan_cong_tenant
           ON phan_cong_nhan_su"""
    )
    cursor.execute(
        """CREATE TRIGGER trg_phan_cong_tenant
           BEFORE INSERT OR UPDATE ON phan_cong_nhan_su
           FOR EACH ROW EXECUTE FUNCTION bf_validate_assignment_target()"""
    )
    cursor.execute(
        """DROP TRIGGER IF EXISTS trg_hop_dong_goi_thau_business
           ON hop_dong_goi_thau"""
    )
    cursor.execute(
        """CREATE TRIGGER trg_hop_dong_goi_thau_business
           BEFORE INSERT OR UPDATE ON hop_dong_goi_thau
           FOR EACH ROW EXECUTE FUNCTION bf_validate_contract_package()"""
    )
    cursor.execute(
        "DROP TRIGGER IF EXISTS trg_audit_log_immutable ON audit_log"
    )
    cursor.execute(
        """CREATE TRIGGER trg_audit_log_immutable
           BEFORE UPDATE OR DELETE ON audit_log
           FOR EACH ROW EXECUTE FUNCTION bf_forbid_audit_mutation()"""
    )
    cursor.execute(
        "DROP TRIGGER IF EXISTS trg_nhat_ky_thuc_hien_immutable ON nhat_ky_thuc_hien"
    )
    cursor.execute(
        """CREATE TRIGGER trg_nhat_ky_thuc_hien_immutable
           BEFORE UPDATE OR DELETE ON nhat_ky_thuc_hien
           FOR EACH ROW EXECUTE FUNCTION bf_forbid_audit_mutation()"""
    )
    for table_name in (
        "procurement_source_revision",
        "procurement_source_binding",
        "procurement_raw_snapshot",
        "word_template_publication_event",
        "generated_document_provenance",
        "legal_instrument_version",
        "legal_source_profile_version",
        "legal_source_profile_member",
        "legal_applicability_policy_version",
        "plan_legal_binding",
        "package_legal_binding",
        "procurement_case_response_revision",
        "procurement_case_transition",
        "procurement_case_attachment",
        "procurement_case_legal_basis",
        "procurement_case_source_observation",
        "procurement_case_command",
        "calendar_event_revision",
        "bulk_operation_item",
    ):
        if table_name not in SCHEMA_DINH_NGHIA:
            continue
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION bf_forbid_audit_mutation()"
        )
    for table_name in (
        "word_template_version",
        "word_template_preflight_run",
    ):
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION bf_forbid_audit_mutation()"
        )
    cursor.execute(
        "DROP TRIGGER IF EXISTS trg_goi_thau_violation_stale ON goi_thau"
    )
    cursor.execute(
        """CREATE TRIGGER trg_goi_thau_violation_stale
           AFTER UPDATE OF thoi_gian_dong_thau ON goi_thau
           FOR EACH ROW EXECUTE FUNCTION bf_mark_contractor_violation_checks_stale()"""
    )
    cursor.execute(
        "DROP TRIGGER IF EXISTS trg_goi_thau_gia_han_violation_stale ON goi_thau_gia_han"
    )


class _HistoricalSchemaCursor:
    """Skip only latest objects whose table/column is not migrated yet."""

    _SAVEPOINT = "bf_historical_schema_object"

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, statement, parameters=None):
        self._cursor.execute(f"SAVEPOINT {self._SAVEPOINT}")
        try:
            result = self._cursor.execute(statement, parameters)
        except (UndefinedColumn, UndefinedTable):
            self._cursor.execute(f"ROLLBACK TO SAVEPOINT {self._SAVEPOINT}")
            self._cursor.execute(f"RELEASE SAVEPOINT {self._SAVEPOINT}")
            return self
        except UndefinedObject as exc:
            self._cursor.execute(f"ROLLBACK TO SAVEPOINT {self._SAVEPOINT}")
            self._cursor.execute(f"RELEASE SAVEPOINT {self._SAVEPOINT}")
            if "gin_trgm_ops" in str(exc):
                return self
            raise
        self._cursor.execute(f"RELEASE SAVEPOINT {self._SAVEPOINT}")
        return result


def create_indexes_and_triggers(cursor) -> None:
    target = cursor
    if _application_tables(cursor) != set(SCHEMA_DINH_NGHIA):
        target = _HistoricalSchemaCursor(cursor)
    _create_indexes(target)
    _create_triggers(target)


def create_commercial_immutable_triggers(cursor) -> None:
    """Create v79 immutable triggers after a fresh canonical install."""
    for table_name in (
        "commercial_releases", "commercial_release_timeline",
        "commercial_policy_versions", "billing_plan_versions", "billing_skus",
        "billing_prices", "payment_provider_profiles", "billing_quotes",
        "payment_transactions", "usage_ledger",
    ):
        cursor.execute(
            f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}"
        )
        cursor.execute(
            f"CREATE TRIGGER trg_{table_name}_immutable "
            f"BEFORE UPDATE OR DELETE ON {table_name} "
            "FOR EACH ROW EXECUTE FUNCTION bf_forbid_audit_mutation()"
        )


def assert_foreign_key_integrity(cursor) -> None:
    invalid = cursor.execute(
        """SELECT conrelid::regclass::text, conname
           FROM pg_constraint
           WHERE contype = 'f' AND NOT convalidated
             AND connamespace = current_schema()::regnamespace
           ORDER BY conrelid::regclass::text, conname"""
    ).fetchall()
    if invalid:
        sample = ", ".join(f"{row[0]}.{row[1]}" for row in invalid[:5])
        raise RuntimeError(f"Unvalidated PostgreSQL foreign keys: {sample}")


def assert_schema_contract(cursor) -> None:
    from backend.db.postgres_schema_contract import (
        assert_catalog_contract,
        load_expected_postgres_schema_catalog,
        read_postgres_schema_catalog,
    )

    actual_catalog = read_postgres_schema_catalog(cursor)
    expected_catalog = load_expected_postgres_schema_catalog()
    assert_catalog_contract(expected_catalog, actual_catalog)


def _schema_object_drift(expected_catalog, actual_catalog):
    from backend.db.postgres_schema_contract import schema_catalog_drift

    comparable_actual = (
        _historical_v46_catalog(actual_catalog)
        if int(expected_catalog.get("schemaVersion") or 0) == 46
        else dict(actual_catalog)
    )
    comparable_actual["schemaVersion"] = expected_catalog.get("schemaVersion")
    return schema_catalog_drift(expected_catalog, comparable_actual)


def _drop_application_constraints(cursor) -> None:
    rows = cursor.execute(
        """SELECT relation.relname, constraint_row.conname,
                  constraint_row.contype
             FROM pg_constraint AS constraint_row
             JOIN pg_class AS relation
               ON relation.oid = constraint_row.conrelid
            WHERE constraint_row.connamespace = current_schema()::regnamespace
            ORDER BY CASE constraint_row.contype WHEN 'f' THEN 0 ELSE 1 END,
                     relation.relname, constraint_row.conname"""
    ).fetchall()
    application_tables = set(SCHEMA_DINH_NGHIA)
    for table_name, constraint_name, _kind in rows:
        if str(table_name) not in application_tables:
            continue
        cursor.execute(
            sql.SQL("ALTER TABLE {} DROP CONSTRAINT {}").format(
                sql.Identifier(str(table_name)),
                sql.Identifier(str(constraint_name)),
            )
        )


def _drop_application_indexes(cursor) -> None:
    rows = cursor.execute(
        """SELECT table_row.relname, index_row.relname
             FROM pg_index AS index_meta
             JOIN pg_class AS index_row ON index_row.oid = index_meta.indexrelid
             JOIN pg_class AS table_row ON table_row.oid = index_meta.indrelid
            WHERE index_row.relnamespace = current_schema()::regnamespace
            ORDER BY table_row.relname, index_row.relname"""
    ).fetchall()
    application_tables = set(SCHEMA_DINH_NGHIA)
    for table_name, index_name in rows:
        if str(table_name) not in application_tables:
            continue
        cursor.execute(
            sql.SQL("DROP INDEX {}").format(sql.Identifier(str(index_name)))
        )


def _reconcile_application_columns(cursor, expected_catalog, actual_catalog) -> None:
    for table_name, expected_table in expected_catalog["tables"].items():
        actual_table = actual_catalog["tables"][table_name]
        for column_name, expected_column in expected_table["columns"].items():
            actual_column = actual_table["columns"].get(column_name)
            if actual_column is None:
                raise RuntimeError(
                    "Historical schema reconciliation requires an explicit "
                    f"backfill for missing column {table_name}.{column_name}."
                )
            table_identifier = sql.Identifier(table_name)
            column_identifier = sql.Identifier(column_name)
            expected_type = str(expected_column["type"])
            if actual_column["type"] != expected_type:
                cursor.execute(
                    sql.SQL(
                        "ALTER TABLE {} ALTER COLUMN {} TYPE {} USING {}::{}"
                    ).format(
                        table_identifier,
                        column_identifier,
                        sql.SQL(expected_type),
                        column_identifier,
                        sql.SQL(expected_type),
                    )
                )
            expected_default = expected_column["default"]
            if actual_column["default"] != expected_default:
                if expected_default is None:
                    cursor.execute(
                        sql.SQL("ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT").format(
                            table_identifier,
                            column_identifier,
                        )
                    )
                else:
                    cursor.execute(
                        sql.SQL(
                            "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {}"
                        ).format(
                            table_identifier,
                            column_identifier,
                            sql.SQL(str(expected_default)),
                        )
                    )
            if bool(actual_column["notNull"]) != bool(expected_column["notNull"]):
                action = "SET NOT NULL" if expected_column["notNull"] else "DROP NOT NULL"
                cursor.execute(
                    sql.SQL("ALTER TABLE {} ALTER COLUMN {} {}").format(
                        table_identifier,
                        column_identifier,
                        sql.SQL(action),
                    )
                )


def _recreate_application_constraints(cursor, expected_catalog) -> None:
    constraints = []
    for table_name, table_spec in expected_catalog["tables"].items():
        for constraint_name, constraint_spec in table_spec["constraints"].items():
            constraints.append((
                str(constraint_spec["kind"]),
                table_name,
                constraint_name,
                str(constraint_spec["definition"]),
            ))
    order = {"p": 0, "u": 1, "c": 2, "x": 3, "f": 4}
    constraints.sort(key=lambda item: (order.get(item[0], 3), item[1], item[2]))
    for _kind, table_name, constraint_name, definition in constraints:
        cursor.execute(
            sql.SQL("ALTER TABLE {} ADD CONSTRAINT {} {}").format(
                sql.Identifier(table_name),
                sql.Identifier(constraint_name),
                sql.SQL(definition),
            )
        )


def _historical_v46_catalog(latest_catalog):
    """Project the latest contract back to the catalog v46 is allowed to build.

    V46 intentionally reconciles the released v1-v45 chain. Later append-only
    migrations must remain owned by their own upgrade step rather than being
    pulled backward into v46 whenever the generated latest contract changes.
    """

    catalog = deepcopy(latest_catalog)
    # These subscription columns were introduced by the v79 commercial
    # backfill.  The replayed v1-v45 chain must reconcile against the
    # immutable pre-commercial v46 catalog; v79 adds them later.
    for table_name in ("account_subscriptions", "organization_subscriptions"):
        table = catalog["tables"].get(table_name)
        if table:
            for column_name in ("plan_version_id", "source", "source_order_id"):
                table["columns"].pop(column_name, None)
            table["constraints"] = {
                name: constraint
                for name, constraint in table["constraints"].items()
                if not any(
                    token in constraint.get("definition", "")
                    for token in ("plan_version_id", "source_order_id", "source =")
                )
            }
    account = catalog["tables"]["tai_khoan"]
    account["columns"].pop("trang_thai", None)
    account["constraints"].pop("tai_khoan_trang_thai_check", None)
    ai_messages = catalog["tables"]["ai_messages"]
    ai_messages["columns"].pop("client_request_id", None)
    ai_messages["constraints"].pop(
        "ai_messages_client_request_id_check", None
    )
    catalog["indexes"].pop("idx_ai_messages_client_request", None)
    websocket_events = catalog["tables"]["websocket_events"]
    websocket_events["columns"].pop("dispatched_at", None)
    status_constraint = websocket_events["constraints"].get(
        "websocket_events_status_check"
    )
    if status_constraint is not None:
        status_constraint["definition"] = (
            "CHECK (status = ANY (ARRAY['pending'::text, 'retry'::text, "
            "'delivered'::text, 'dead_letter'::text]))"
        )
    post_v46_tables = {
        # Commercial/billing/usage tables were introduced in v79 and must not
        # be pulled into the immutable v46 historical replay projection.
        "commercial_drafts",
        "commercial_releases",
        "commercial_release_timeline",
        "commercial_policy_versions",
        "billing_plan_versions",
        "billing_skus",
        "billing_prices",
        "payment_provider_profiles",
        "billing_quotes",
        "billing_orders",
        "billing_order_items",
        "billing_provider_commands",
        "payment_transactions",
        "payment_webhook_events",
        "billing_subscription_activations",
        "billing_refund_intents",
        "usage_credit_grants",
        "usage_reservations",
        "usage_ledger",
        "billing_invoice_requests",
        "commercial_outbox",
        "procurement_source_revision",
        "procurement_source_binding",
        "procurement_import_operation",
        "procurement_raw_snapshot",
        "conflict_resolution_drafts",
        "word_template",
        "word_template_version",
        "word_template_preflight_run",
        "word_template_publication_event",
        "word_template_projection_outbox",
        "word_publication_assignment_v2",
        "word_template_assignment_config",
        "generated_document_provenance",
        "legal_instrument",
        "legal_instrument_draft",
        "legal_instrument_version",
        "legal_source_profile",
        "legal_source_profile_draft",
        "legal_source_profile_version",
        "legal_source_profile_member",
        "legal_applicability_policy_version",
        "plan_legal_binding",
        "package_legal_binding",
        "plan_legal_binding_head",
        "package_legal_binding_head",
        "procurement_case",
        "procurement_case_package_target",
        "procurement_case_party",
        "procurement_case_responsibility",
        "procurement_case_response_revision",
        "procurement_case_transition",
        "procurement_case_attachment",
        "procurement_case_legal_basis",
        "procurement_case_source_observation",
        "procurement_case_command",
        "calendar_event_head",
        "calendar_event_revision",
        "bulk_operation",
        "bulk_operation_item",
        "bulk_operation_artifact",
        "calendar_oauth_state",
        "calendar_connection",
        "calendar_event_binding",
        "calendar_delivery_outbox",
    }
    for table_name in post_v46_tables:
        catalog["tables"].pop(table_name, None)
    catalog["indexes"] = {
        name: spec
        for name, spec in catalog["indexes"].items()
        if spec.get("table") not in post_v46_tables
    }
    catalog["triggers"] = {
        name: spec
        for name, spec in catalog["triggers"].items()
        if spec.get("table") not in post_v46_tables
    }
    catalog["schemaVersion"] = 46
    return catalog


def reconcile_historical_postgres_schema(cursor) -> tuple[str, ...]:
    """Reconcile a replayed historical chain to the immutable v46 catalog."""

    from backend.db.postgres_schema_contract import (
        load_expected_postgres_schema_catalog,
        read_postgres_schema_catalog,
    )

    expected_catalog = _historical_v46_catalog(
        load_expected_postgres_schema_catalog()
    )
    actual_catalog = read_postgres_schema_catalog(cursor)
    initial_drift = _schema_object_drift(expected_catalog, actual_catalog)
    if not initial_drift:
        return ()

    for table_name, table_spec in SCHEMA_DINH_NGHIA.items():
        if table_name not in expected_catalog["tables"]:
            continue
        if table_name in actual_catalog["tables"]:
            continue
        cursor.execute(build_create_table_sql(table_name, table_spec))

    actual_catalog = read_postgres_schema_catalog(cursor)
    _drop_application_constraints(cursor)
    _drop_application_indexes(cursor)
    _reconcile_application_columns(cursor, expected_catalog, actual_catalog)
    _recreate_application_constraints(cursor, expected_catalog)
    schema_name = str(cursor.execute("SELECT current_schema()").fetchone()[0])
    cursor.execute(
        sql.SQL("SET LOCAL search_path TO {}, public").format(
            sql.Identifier(schema_name)
        )
    )
    create_indexes_and_triggers(cursor)
    cursor.execute(
        sql.SQL("SET LOCAL search_path TO {}").format(
            sql.Identifier(schema_name)
        )
    )

    remaining_drift = _schema_object_drift(
        expected_catalog,
        read_postgres_schema_catalog(cursor),
    )
    if remaining_drift:
        raise RuntimeError(
            "Historical schema reconciliation remained incomplete: "
            + "; ".join(remaining_drift[:12])
        )
    return initial_drift


def _application_tables(cursor) -> set[str]:
    return {
        row[0]
        for row in cursor.execute(
            """SELECT table_name FROM information_schema.tables
               WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'"""
        ).fetchall()
        if row[0] in SCHEMA_DINH_NGHIA
    }


def create_fresh_database(cursor, context: DatabaseUpgradeContext) -> int:
    from backend.auth.auth_helper import hash_password
    from backend.auth.identity import normalize_email, normalize_username
    from backend.auth.password_policy import validate_new_password
    from backend.db.id_utils import generate_record_id, stable_org_id

    existing = _application_tables(cursor)
    if existing:
        raise RuntimeError(
            "The PostgreSQL fresh-install baseline requires an empty schema; existing tables: "
            + ", ".join(sorted(existing))
        )
    _create_extensions(cursor)
    for table_name, table_spec in SCHEMA_DINH_NGHIA.items():
        cursor.execute(context.build_create_table_sql(table_name, table_spec))
    _create_foreign_keys(cursor)

    cursor.executemany(
        """INSERT INTO goi_dich_vu
           (id, ten_goi, gia_ca, han_muc_nhan_su, mo_ta)
           VALUES (%s, %s, %s, %s, %s)""",
        (
            ("silver", "Gói Bạc (Silver)", 15_000_000, 5, "Phù hợp với đơn vị quy mô nhỏ, quản lý tối đa 5 nhân sự."),
            ("gold", "Gói Vàng (Gold)", 35_000_000, 15, "Giải pháp cho phòng thầu chuyên nghiệp, tối đa 15 nhân sự."),
            ("diamond", "Gói Kim Cương (Diamond)", 75_000_000, 999, "Gói quản trị không giới hạn số lượng nhân sự."),
        ),
    )
    admin_password = os.environ.get("ADMIN_PASSWORD", "")
    password_valid, password_error = validate_new_password(admin_password)
    if not password_valid:
        raise RuntimeError(
            f"ADMIN_PASSWORD does not satisfy password policy: {password_error}"
        )
    admin_id = generate_record_id("tai_khoan")
    admin_name = os.environ.get("ADMIN_NAME", "Administrator").strip() or "Administrator"
    admin_username = normalize_username(os.environ.get("ADMIN_USERNAME", "admin"))
    admin_email = normalize_email(os.environ.get("ADMIN_EMAIL", "admin@localhost"))
    organization_name = os.environ.get("DEFAULT_ORG_NAME", "HCP").strip() or "HCP"
    organization_id = stable_org_id(organization_name)
    cursor.execute(
        """INSERT INTO tai_khoan (
             id, ten_dang_nhap, username_norm, mat_khau, ho_ten, vai_tro,
             email, email_norm, da_xac_minh
           ) VALUES (%s, %s, %s, %s, %s, 'super_admin', %s, %s, 1)""",
        (
            admin_id,
            admin_username,
            admin_username,
            hash_password(admin_password),
            admin_name,
            admin_email,
            admin_email,
        ),
    )
    cursor.execute(
        "INSERT INTO to_chuc (id, ten_to_chuc) VALUES (%s, %s)",
        (organization_id, organization_name),
    )
    for status_name, color in DEFAULT_CONTRACT_STATUSES:
        status_id = "tthd-" + sha256(
            f"{organization_id}:{status_name}".encode("utf-8")
        ).hexdigest()[:32]
        cursor.execute(
            """INSERT INTO danh_muc_trang_thai_hop_dong
                   (id, organization_id, owner_type, name, color)
               VALUES (%s, %s, 'organization', %s, %s)""",
            (status_id, organization_id, status_name, color),
        )
    cursor.execute(
        """INSERT INTO thanh_vien_to_chuc
           (user_id, organization_id, vai_tro_trong_to_chuc)
           VALUES (%s, %s, 'manager')""",
        (admin_id, organization_id),
    )
    now = int(time.time())
    cursor.execute(
        """INSERT INTO organization_subscriptions (
             organization_id, package_id, status, starts_at, expires_at, member_quota
           ) VALUES (%s, 'diamond', 'active', %s, %s, 999)""",
        (organization_id, now, now + 3650 * 24 * 60 * 60),
    )
    cursor.execute(
        "INSERT INTO sync_metadata (organization_id, current_version) VALUES (%s, 1)",
        (organization_id,),
    )
    ensure_commercial_v79_indexes(cursor)
    seed_commercial_v79(cursor)
    seed_live_payos_v80_profile(cursor)
    context.create_indexes_and_triggers(cursor)
    create_commercial_immutable_triggers(cursor)
    drop_retired_procurement_center_schema(cursor)
    record_database_version(cursor, DB_SCHEMA_VERSION)
    context.assert_foreign_key_integrity(cursor)
    return DB_SCHEMA_VERSION


def initialize_postgres_database(database, *, dry_run: bool = False) -> int:
    connection = None
    try:
        connection = database.get_connection()
        cursor = connection.cursor()
        cursor.execute("BEGIN")
        cursor.execute(
            "SELECT pg_advisory_xact_lock(hashtext('biddingflow-schema-upgrade'))"
        )
        context = DatabaseUpgradeContext(
            build_create_table_sql=build_create_table_sql,
            create_indexes_and_triggers=create_indexes_and_triggers,
            assert_foreign_key_integrity=assert_foreign_key_integrity,
            create_foreign_keys=_create_foreign_keys,
            create_trigger_functions=_create_trigger_functions,
            create_synced_delete_trigger_function=(
                _create_synced_delete_trigger_function
            ),
        )
        installed_version = read_database_version(cursor)
        if installed_version is None:
            version = create_fresh_database(cursor, context)
        else:
            version = apply_database_upgrades(cursor, installed_version, context)
        if version != DB_SCHEMA_VERSION:
            raise RuntimeError(
                f"Database initialization stopped at unexpected version {version}."
            )
        # Idempotently repair immutable v79 commercial triggers on databases
        # upgraded before the trigger set was added to the canonical contract.
        if version >= 79:
            create_commercial_immutable_triggers(cursor)
        assert_schema_contract(cursor)
        assert_foreign_key_integrity(cursor)
        if dry_run:
            connection.rollback()
        else:
            connection.commit()
        return version
    except Exception:
        if connection is not None:
            connection.rollback()
        raise
    finally:
        if connection is not None:
            connection.close()


def initialize_and_log(database) -> None:
    try:
        version = initialize_postgres_database(database)
        log_error(
            f"PostgreSQL schema ready (version {version}).",
            "Database",
            level="INFO",
        )
    except Exception as exc:
        log_error(exc, "Database.Migration")
        raise
