import fs from 'node:fs';
import vm from 'node:vm';
import { createHash } from 'node:crypto';

// Use the repository-pinned Lucide geometry; no network or runtime icon library.
const context = {};
vm.runInNewContext(fs.readFileSync('views/vendor/lucide/lucide.min.js', 'utf8'), context);
const markup = fs.readFileSync('views/components/landing_page.html', 'utf8');
const names = [...new Set([
  ...[...markup.matchAll(/data-lucide="([^"]+)"/g)].map(match => match[1]),
  'info', 'check', 'layers-3', 'arrow-right', 'menu',
])].sort();
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const symbols = names.map(name => {
  const key = name.replace(/(^|-)([a-z0-9])/g, (_, _prefix, letter) => letter.toUpperCase());
  const nodes = context.lucide.icons[key];
  if (!nodes) throw new Error(`Unknown pinned Lucide icon: ${name}`);
  return `  <symbol id="icon-${name}" viewBox="0 0 24 24">${nodes.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).filter(([attr]) => attr !== 'key').map(([attr, value]) => `${attr}="${escape(value)}"`).join(' ')}/>`).join('')}</symbol>`;
});
const sprite = `<svg xmlns="http://www.w3.org/2000/svg"><!-- Generated from pinned Lucide. See views/vendor/lucide for license. -->\n${symbols.join('\n')}\n</svg>\n`;
const hash = createHash('sha256').update(sprite).digest('hex');
const manifest = `// Generated by scripts/generate_landing_icons.mjs.\nexport const LANDING_ICON_NAMES = Object.freeze(${JSON.stringify(names)});\nexport const LANDING_ICON_VERSION = "${hash}";\n`;
for (const [file, content] of [['views/assets/landing-icons.svg', sprite], ['frontend/landing/landingIconManifest.js', manifest]]) {
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) throw new Error(`Regenerate ${file}`);
  } else fs.writeFileSync(file, content);
}
console.log(`Landing icons: ${names.length} verified symbols.`);
