/* Generated from backend/helpers_py/schema.py. Do not edit by hand. */
export const SCHEMA_CONTRACT = {
  "clientTableMap": {
    "assignments": "phan_cong_nhan_su",
    "chudautu": "chu_dau_tu",
    "chuyengia": "chuyen_gia",
    "custompaperstatuses": "trang_thai_ho_so_giay",
    "employees": "tai_khoan",
    "goithau": "goi_thau",
    "hopdong": "hop_dong",
    "kehoach": "ke_hoach_lcnt",
    "nhathau": "nha_thau",
    "organizations": "to_chuc",
    "permissionmatrix": "ma_tran_phan_quyen",
    "systempackages": "goi_dich_vu",
    "thongtinmothau": "thong_tin_mo_thau"
  },
  "commonFieldMap": {
    "actor_user_id": "actorUserId",
    "anh_chu_ky": "anhChuKy",
    "anh_chung_chi": "anhChungChi",
    "anh_dai_dien": "anhDaiDien",
    "bao_dam_du_thau": "baoDamDuThau",
    "chu_dau_tu_id": "chuDauTuId",
    "chuc_vu": "chucVu",
    "chuc_vu_dai_dien": "chucVuDaiDien",
    "chuc_vu_nguoi_dung_dau": "chucVuNguoiDungDau",
    "chuyen_gia_id": "chuyenGiaId",
    "client_mutation_id": "clientMutationId",
    "co_qd_chi_dinh": "coQdChiDinh",
    "co_quan_chu_quan": "coQuanChuQuan",
    "co_quan_phe_duyet_du_an": "coQuanPheDuyetDuAn",
    "cong_viec": "congViec",
    "created_at": "createdAt",
    "current_version": "currentVersion",
    "da_xac_minh": "daXacMinh",
    "dai_dien_cdt": "daiDienCdt",
    "dam_bao_du_thau": "damBaoDuThau",
    "danh_gia_hop_le": "danhGiaHopLe",
    "danh_gia_hsdt_metadata": "danhGiaHsdtMetadata",
    "danh_gia_ket_luan": "danhGiaKetLuan",
    "danh_gia_ky_thuat": "danhGiaKyThuat",
    "danh_gia_nang_luc": "danhGiaNangLuc",
    "danh_gia_tai_chinh": "danhGiaTaiChinh",
    "danh_xung": "danhXung",
    "delete_version": "deleteVersion",
    "deleted_at": "deletedAt",
    "dia_chi": "diaChi",
    "dia_chi_goc": "diaChiGoc",
    "dia_diem_quy_mo": "diaDiemQuyMo",
    "don_vi": "donVi",
    "don_vi_cap_chung_chi": "donViCapChungChi",
    "don_vi_thuc_hien": "donViThucHien",
    "don_vi_trinh_cdt": "donViTrinhCdt",
    "emp_id": "empId",
    "gia_ca": "giaCa",
    "gia_du_thau": "giaDuThau",
    "gia_goi_thau": "giaGoiThau",
    "gia_sau_giam_gia": "giaSauGiamGia",
    "gia_tri": "giaTri",
    "gia_tri_dam_bao": "giaTriDamBao",
    "gia_tri_dam_bao_du_thau": "giaTriDamBaoDuThau",
    "gia_tri_phan_lo": "giaTriPhanLo",
    "gia_tri_uoc_tinh": "giaTriUocTinh",
    "gia_trung_thau": "giaTrungThau",
    "goi_dich_vu_id": "goiDichVuId",
    "goi_thau_id": "goiThauId",
    "google_id": "googleId",
    "han_muc_nhan_su": "hanMucNhanSu",
    "han_su_dung_token": "hanSuDungToken",
    "han_xac_minh": "hanXacMinh",
    "hang_muc": "hangMuc",
    "hieu_luc_bao_dam_ngay": "hieuLucBaoDamNgay",
    "hieu_luc_dam_bao": "hieuLucDamBao",
    "hieu_luc_dam_bao_du_thau": "hieuLucDamBaoDuThau",
    "hieu_luc_hsdt": "hieuLucHsdt",
    "hieu_luc_hsdxt": "hieuLucHsdxt",
    "hinh_thuc_lua_chon": "hinhThucLuaChon",
    "ho_ten": "hoTen",
    "hop_dong_id": "hopDongId",
    "id_goc": "rootId",
    "id_muc_tieu": "targetId",
    "id_nhan_vien": "empId",
    "ip_address": "ipAddress",
    "is_latest": "isLatest",
    "is_thuoc": "isThuoc",
    "is_tong_muc_tu_dong": "isTongMucTuDong",
    "ke_hoach_id": "keHoachId",
    "lam_ro_hop_le": "lamRoHopLe",
    "lam_ro_ky_thuat": "lamRoKyThuat",
    "lam_ro_nang_luc": "lamRoNangLuc",
    "lam_ro_tai_chinh": "lamRoTaiChinh",
    "linh_vuc": "linhVuc",
    "loai_doi_tuong": "type",
    "loai_hinh_mua_sam": "loaiHinhMuaSam",
    "loai_hop_dong": "loaiHopDong",
    "loai_nha_thau": "loaiNhaThau",
    "ly_do_gia_han": "lyDoGiaHan",
    "ly_do_truot": "lyDoTruot",
    "ma_chu_dau_tu": "maChuDauTu",
    "ma_dinh_danh": "maDinhDanh",
    "ma_du_an": "maDuAn",
    "ma_goi_thau": "maGoiThau",
    "ma_ke_hoach": "maKeHoach",
    "ma_ngan_hang": "maNganHang",
    "ma_nha_thau": "maNhaThau",
    "ma_phan_lo": "maPhanLo",
    "ma_qhns": "maQHNS",
    "ma_so_thue": "maSoThue",
    "ma_xac_minh": "maXacMinh",
    "mat_khau": "matKhau",
    "metadata_json": "metadataJson",
    "mo_ta": "moTa",
    "ngay_bao_cao_tham_dinh_hsmt": "ngayBaoCaoThamDinhHsmt",
    "ngay_bat_dau_goi": "ngayBatDauGoi",
    "ngay_cap_cccd": "ngayCapCCCD",
    "ngay_cap_chung_chi": "ngayCapChungChi",
    "ngay_het_han_goi": "ngayHetHanGoi",
    "ngay_ky": "ngayKy",
    "ngay_phe_duyet": "ngayPheDuyet",
    "ngay_phe_duyet_du_toan": "ngayPheDuyetDuToan",
    "ngay_qd_chi_dinh": "ngayQdChiDinh",
    "ngay_qd_phe_duyet_du_an": "ngayQdPheDuyetDuAn",
    "ngay_quyet_dinh": "ngayQuyetDinh",
    "ngay_quyet_dinh_ket_qua": "ngayQuyetDinhKetQua",
    "ngay_trinh_du_toan": "ngayTrinhDuToan",
    "ngay_trinh_hsmt": "ngayTrinhHsmt",
    "ngay_trinh_ke_hoach": "ngayTrinhKeHoach",
    "nguoi_dai_dien": "nguoiDaiDien",
    "nguon_von": "nguonVon",
    "nguyen_nhan_khong_dat_hop_le": "nguyenNhanKhongDatHopLe",
    "nguyen_nhan_khong_dat_ky_thuat": "nguyenNhanKhongDatKyThuat",
    "nguyen_nhan_khong_dat_nang_luc": "nguyenNhanKhongDatNangLuc",
    "nha_thau_id": "nhaThauId",
    "nha_thau_trung_thau_id": "nhaThauTrungThauId",
    "noi_cap_cccd": "noiCapCCCD",
    "noi_dung": "noiDung",
    "noi_mo_tai_khoan": "noiMoTaiKhoan",
    "owner_id": "ownerId",
    "owner_type": "ownerType",
    "phan_lo": "phanLo",
    "phan_loai": "phanLoai",
    "phe_duyet": "pheDuyet",
    "phien_ban": "phienBan",
    "phuong_phap_danh_gia": "phuongPhapDanhGia",
    "phuong_thuc_lua_chon": "phuongThucLuaChon",
    "quan_ly_id": "quanLyId",
    "quyet_dinh_phe_duyet": "quyetDinhPheDuyet",
    "record_id": "recordId",
    "response_json": "responseJson",
    "root_id": "rootId",
    "so_bao_cao_tham_dinh_hsmt": "soBaoCaoThamDinhHsmt",
    "so_cccd": "soCCCD",
    "so_chung_chi": "soChungChi",
    "so_dien_thoai": "soDienThoai",
    "so_hop_dong": "soHopDong",
    "so_luong": "soLuong",
    "so_qd_chi_dinh": "soQdChiDinh",
    "so_qd_phe_duyet_du_an": "soQdPheDuyetDuAn",
    "so_qd_phe_duyet_du_toan": "soQdPheDuyetDuToan",
    "so_quyet_dinh": "soQuyetDinh",
    "so_quyet_dinh_ket_qua": "soQuyetDinhKetQua",
    "so_tai_khoan": "soTaiKhoan",
    "so_to_trinh_hsmt": "soToTrinhHsmt",
    "sort_order": "sortOrder",
    "source_column": "sourceColumn",
    "source_table": "sourceTable",
    "sync_version": "syncVersion",
    "table_name": "tableName",
    "target_id": "targetId",
    "target_type": "targetType",
    "ten_anh_chu_ky": "tenAnhChuKy",
    "ten_anh_chung_chi": "tenAnhChungChi",
    "ten_bien": "tenBien",
    "ten_chu_dau_tu": "tenChuDauTu",
    "ten_cong_viec": "tenCongViec",
    "ten_dang_nhap": "tenDangNhap",
    "ten_du_an_du_toan": "tenDuAnDuToan",
    "ten_goi": "tenGoi",
    "ten_goi_thau": "tenGoiThau",
    "ten_hop_dong": "tenHopDong",
    "ten_ke_hoach": "tenKeHoach",
    "ten_nha_thau": "tenNhaThau",
    "ten_phan_lo": "tenPhanLo",
    "ten_to_chuc": "tenToChuc",
    "ten_viet_tat": "tenVietTat",
    "ten_viet_tat_don_vi_trinh": "tenVietTatDonViTrinh",
    "thoi_gian": "thoiGian",
    "thoi_gian_bat_dau_to_chuc": "thoiGianBatDauToChuc",
    "thoi_gian_dong_thau": "thoiGianDongThau",
    "thoi_gian_du_an": "thoiGianDuAn",
    "thoi_gian_goi_thau": "thoiGianGoiThau",
    "thoi_gian_hop_dong": "thoiGianHopDong",
    "thoi_gian_mo_ehsdxtc": "thoiGianMoEhsdxtc",
    "thoi_gian_mo_thau": "thoiGianMoThau",
    "thoi_gian_to_chuc": "thoiGianToChuc",
    "thong_tin_khac": "thongTinKhac",
    "thong_tin_mo_thau_id": "thongTinMoThauId",
    "thong_tin_thiet_bi_cuoi": "thongTinThietBiCuoi",
    "to_chuc_id": "toChucId",
    "token_phien": "tokenPhien",
    "tong_muc_dau_tu": "tongMucDauTu",
    "trang_thai": "trangThai",
    "trang_thai_ho_so": "trangThaiHoSo",
    "trong_so_ky_thuat": "trongSoKyThuat",
    "tuy_chon_mua_them": "tuyChonMuaThem",
    "ty_le": "tyLe",
    "ty_le_bao_dam_hop_dong": "tyLeBaoDamHopDong",
    "ty_le_giam_gia": "tyLeGiamGia",
    "updated_at": "updatedAt",
    "user_id": "userId",
    "username_da_dat": "usernameDaDat",
    "vai_tro": "vaiTro",
    "vai_tro_trong_to_chuc": "vaiTroTrongToChuc",
    "van_ban_phe_duyet": "vanBanPheDuyet",
    "yeu_cau_tham_dinh_hsmt": "yeuCauThamDinhHsmt"
  },
  "tables": {
    "audit_log": {
      "columns": [
        "id",
        "actor_user_id",
        "owner_id",
        "action",
        "target_type",
        "target_id",
        "ip_address",
        "metadata_json",
        "created_at"
      ],
      "fieldMap": {
        "action": "action",
        "actor_user_id": "actorUserId",
        "created_at": "createdAt",
        "id": "id",
        "ip_address": "ipAddress",
        "metadata_json": "metadataJson",
        "owner_id": "ownerId",
        "target_id": "targetId",
        "target_type": "targetType"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "action": "action",
        "actorUserId": "actor_user_id",
        "createdAt": "created_at",
        "id": "id",
        "ipAddress": "ip_address",
        "metadataJson": "metadata_json",
        "ownerId": "owner_id",
        "targetId": "target_id",
        "targetType": "target_type"
      }
    },
    "cau_hinh_bien_word": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "ten_bien",
        "source_table",
        "source_column",
        "mo_ta",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "id": "id",
        "mo_ta": "moTa",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "source_column": "sourceColumn",
        "source_table": "sourceTable",
        "ten_bien": "tenBien",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "id": "id",
        "moTa": "mo_ta",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "sourceColumn": "source_column",
        "sourceTable": "source_table",
        "tenBien": "ten_bien",
        "updatedAt": "updated_at"
      }
    },
    "chu_dau_tu": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "phien_ban",
        "is_latest",
        "ma_chu_dau_tu",
        "ten_chu_dau_tu",
        "ten_viet_tat",
        "ma_so_thue",
        "chuc_vu_nguoi_dung_dau",
        "dai_dien_cdt",
        "chuc_vu_dai_dien",
        "danh_xung",
        "dia_chi",
        "dia_chi_goc",
        "so_dien_thoai",
        "so_tai_khoan",
        "noi_mo_tai_khoan",
        "email",
        "ma_qhns",
        "co_quan_chu_quan",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "chuc_vu_dai_dien": "chucVuDaiDien",
        "chuc_vu_nguoi_dung_dau": "chucVuNguoiDungDau",
        "co_quan_chu_quan": "coQuanChuQuan",
        "created_at": "createdAt",
        "dai_dien_cdt": "daiDienCdt",
        "danh_xung": "danhXung",
        "dia_chi": "diaChi",
        "dia_chi_goc": "diaChiGoc",
        "email": "email",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "ma_chu_dau_tu": "maChuDauTu",
        "ma_qhns": "maQHNS",
        "ma_so_thue": "maSoThue",
        "noi_mo_tai_khoan": "noiMoTaiKhoan",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phien_ban": "phienBan",
        "so_dien_thoai": "soDienThoai",
        "so_tai_khoan": "soTaiKhoan",
        "sync_version": "syncVersion",
        "ten_chu_dau_tu": "tenChuDauTu",
        "ten_viet_tat": "tenVietTat",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "chucVuDaiDien": "chuc_vu_dai_dien",
        "chucVuNguoiDungDau": "chuc_vu_nguoi_dung_dau",
        "coQuanChuQuan": "co_quan_chu_quan",
        "createdAt": "created_at",
        "daiDienCdt": "dai_dien_cdt",
        "danhXung": "danh_xung",
        "diaChi": "dia_chi",
        "diaChiGoc": "dia_chi_goc",
        "email": "email",
        "id": "id",
        "isLatest": "is_latest",
        "maChuDauTu": "ma_chu_dau_tu",
        "maQHNS": "ma_qhns",
        "maSoThue": "ma_so_thue",
        "noiMoTaiKhoan": "noi_mo_tai_khoan",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "phienBan": "phien_ban",
        "rootId": "id_goc",
        "soDienThoai": "so_dien_thoai",
        "soTaiKhoan": "so_tai_khoan",
        "syncVersion": "sync_version",
        "tenChuDauTu": "ten_chu_dau_tu",
        "tenVietTat": "ten_viet_tat",
        "updatedAt": "updated_at"
      }
    },
    "chuyen_gia": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "phien_ban",
        "is_latest",
        "ho_ten",
        "so_chung_chi",
        "ngay_cap_chung_chi",
        "don_vi_cap_chung_chi",
        "so_cccd",
        "ngay_cap_cccd",
        "noi_cap_cccd",
        "anh_chung_chi",
        "ten_anh_chung_chi",
        "anh_chu_ky",
        "ten_anh_chu_ky",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "anh_chu_ky": "anhChuKy",
        "anh_chung_chi": "anhChungChi",
        "created_at": "createdAt",
        "don_vi_cap_chung_chi": "donViCapChungChi",
        "ho_ten": "hoTen",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "ngay_cap_cccd": "ngayCapCCCD",
        "ngay_cap_chung_chi": "ngayCapChungChi",
        "noi_cap_cccd": "noiCapCCCD",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phien_ban": "phienBan",
        "so_cccd": "soCCCD",
        "so_chung_chi": "soChungChi",
        "sync_version": "syncVersion",
        "ten_anh_chu_ky": "tenAnhChuKy",
        "ten_anh_chung_chi": "tenAnhChungChi",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "anhChuKy": "anh_chu_ky",
        "anhChungChi": "anh_chung_chi",
        "createdAt": "created_at",
        "donViCapChungChi": "don_vi_cap_chung_chi",
        "hoTen": "ho_ten",
        "id": "id",
        "isLatest": "is_latest",
        "ngayCapCCCD": "ngay_cap_cccd",
        "ngayCapChungChi": "ngay_cap_chung_chi",
        "noiCapCCCD": "noi_cap_cccd",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "phienBan": "phien_ban",
        "rootId": "id_goc",
        "soCCCD": "so_cccd",
        "soChungChi": "so_chung_chi",
        "syncVersion": "sync_version",
        "tenAnhChuKy": "ten_anh_chu_ky",
        "tenAnhChungChi": "ten_anh_chung_chi",
        "updatedAt": "updated_at"
      }
    },
    "deleted_records": {
      "columns": [
        "id",
        "table_name",
        "record_id",
        "owner_id",
        "delete_version",
        "deleted_at"
      ],
      "fieldMap": {
        "delete_version": "deleteVersion",
        "deleted_at": "deletedAt",
        "id": "id",
        "owner_id": "ownerId",
        "record_id": "recordId",
        "table_name": "tableName"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "deleteVersion": "delete_version",
        "deletedAt": "deleted_at",
        "id": "id",
        "ownerId": "owner_id",
        "recordId": "record_id",
        "tableName": "table_name"
      }
    },
    "goi_dich_vu": {
      "columns": [
        "id",
        "ten_goi",
        "gia_ca",
        "han_muc_nhan_su",
        "mo_ta",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "gia_ca": "giaCa",
        "han_muc_nhan_su": "hanMucNhanSu",
        "id": "id",
        "mo_ta": "moTa",
        "ten_goi": "tenGoi",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "giaCa": "gia_ca",
        "hanMucNhanSu": "han_muc_nhan_su",
        "id": "id",
        "moTa": "mo_ta",
        "tenGoi": "ten_goi",
        "updatedAt": "updated_at"
      }
    },
    "goi_thau": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "ma_goi_thau",
        "phien_ban",
        "is_latest",
        "ke_hoach_id",
        "ten_goi_thau",
        "gia_goi_thau",
        "loai_hop_dong",
        "hinh_thuc_lua_chon",
        "phuong_thuc_lua_chon",
        "thoi_gian_thuc_hien",
        "nguon_von",
        "nha_thau_trung_thau_id",
        "gia_trung_thau",
        "linh_vuc",
        "tuy_chon_mua_them",
        "thoi_gian_to_chuc",
        "thoi_gian_bat_dau_to_chuc",
        "phan_lo",
        "thoi_gian_dang_tai",
        "thoi_gian_dong_thau",
        "thoi_gian_mo_thau",
        "thoi_gian_mo_ehsdxtc",
        "so_quyet_dinh",
        "ngay_quyet_dinh",
        "so_quyet_dinh_ket_qua",
        "ngay_quyet_dinh_ket_qua",
        "thoi_gian_goi_thau",
        "thoi_gian_hop_dong",
        "gia_tri_dam_bao_du_thau",
        "hieu_luc_hsdt",
        "hieu_luc_dam_bao_du_thau",
        "danh_gia_hsdt_metadata",
        "phuong_phap_danh_gia",
        "trong_so_ky_thuat",
        "ty_le_bao_dam_hop_dong",
        "is_thuoc",
        "trang_thai",
        "yeu_cau_tham_dinh_hsmt",
        "so_bao_cao_tham_dinh_hsmt",
        "ngay_bao_cao_tham_dinh_hsmt",
        "so_to_trinh_hsmt",
        "ngay_trinh_hsmt",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "danh_gia_hsdt_metadata": "danhGiaHsdtMetadata",
        "gia_goi_thau": "giaGoiThau",
        "gia_tri_dam_bao_du_thau": "giaTriDamBaoDuThau",
        "gia_trung_thau": "giaTrungThau",
        "hieu_luc_dam_bao_du_thau": "hieuLucDamBaoDuThau",
        "hieu_luc_hsdt": "hieuLucHsdt",
        "hinh_thuc_lua_chon": "hinhThucLuaChon",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "is_thuoc": "isThuoc",
        "ke_hoach_id": "keHoachId",
        "linh_vuc": "linhVuc",
        "loai_hop_dong": "loaiHopDong",
        "ma_goi_thau": "maGoiThau",
        "ngay_bao_cao_tham_dinh_hsmt": "ngayBaoCaoThamDinhHsmt",
        "ngay_quyet_dinh": "ngayQuyetDinh",
        "ngay_quyet_dinh_ket_qua": "ngayQuyetDinhKetQua",
        "ngay_trinh_hsmt": "ngayTrinhHsmt",
        "nguon_von": "nguonVon",
        "nha_thau_trung_thau_id": "nhaThauTrungThauId",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phan_lo": "phanLo",
        "phien_ban": "phienBan",
        "phuong_phap_danh_gia": "phuongPhapDanhGia",
        "phuong_thuc_lua_chon": "phuongThucLuaChon",
        "so_bao_cao_tham_dinh_hsmt": "soBaoCaoThamDinhHsmt",
        "so_quyet_dinh": "soQuyetDinh",
        "so_quyet_dinh_ket_qua": "soQuyetDinhKetQua",
        "so_to_trinh_hsmt": "soToTrinhHsmt",
        "sync_version": "syncVersion",
        "ten_goi_thau": "tenGoiThau",
        "thoi_gian_bat_dau_to_chuc": "thoiGianBatDauToChuc",
        "thoi_gian_dang_tai": "thoiGianDangTai",
        "thoi_gian_dong_thau": "thoiGianDongThau",
        "thoi_gian_goi_thau": "thoiGianGoiThau",
        "thoi_gian_hop_dong": "thoiGianHopDong",
        "thoi_gian_mo_ehsdxtc": "thoiGianMoEhsdxtc",
        "thoi_gian_mo_thau": "thoiGianMoThau",
        "thoi_gian_thuc_hien": "thoiGianThucHien",
        "thoi_gian_to_chuc": "thoiGianToChuc",
        "trang_thai": "trangThai",
        "trong_so_ky_thuat": "trongSoKyThuat",
        "tuy_chon_mua_them": "tuyChonMuaThem",
        "ty_le_bao_dam_hop_dong": "tyLeBaoDamHopDong",
        "updated_at": "updatedAt",
        "yeu_cau_tham_dinh_hsmt": "yeuCauThamDinhHsmt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "danhGiaHsdtMetadata": "danh_gia_hsdt_metadata",
        "giaGoiThau": "gia_goi_thau",
        "giaTriDamBaoDuThau": "gia_tri_dam_bao_du_thau",
        "giaTrungThau": "gia_trung_thau",
        "hieuLucDamBaoDuThau": "hieu_luc_dam_bao_du_thau",
        "hieuLucHsdt": "hieu_luc_hsdt",
        "hinhThucLuaChon": "hinh_thuc_lua_chon",
        "id": "id",
        "isLatest": "is_latest",
        "isThuoc": "is_thuoc",
        "keHoachId": "ke_hoach_id",
        "linhVuc": "linh_vuc",
        "loaiHopDong": "loai_hop_dong",
        "maGoiThau": "ma_goi_thau",
        "ngayBaoCaoThamDinhHsmt": "ngay_bao_cao_tham_dinh_hsmt",
        "ngayQuyetDinh": "ngay_quyet_dinh",
        "ngayQuyetDinhKetQua": "ngay_quyet_dinh_ket_qua",
        "ngayTrinhHsmt": "ngay_trinh_hsmt",
        "nguonVon": "nguon_von",
        "nhaThauTrungThauId": "nha_thau_trung_thau_id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "phanLo": "phan_lo",
        "phienBan": "phien_ban",
        "phuongPhapDanhGia": "phuong_phap_danh_gia",
        "phuongThucLuaChon": "phuong_thuc_lua_chon",
        "rootId": "id_goc",
        "soBaoCaoThamDinhHsmt": "so_bao_cao_tham_dinh_hsmt",
        "soQuyetDinh": "so_quyet_dinh",
        "soQuyetDinhKetQua": "so_quyet_dinh_ket_qua",
        "soToTrinhHsmt": "so_to_trinh_hsmt",
        "syncVersion": "sync_version",
        "tenGoiThau": "ten_goi_thau",
        "thoiGianBatDauToChuc": "thoi_gian_bat_dau_to_chuc",
        "thoiGianDangTai": "thoi_gian_dang_tai",
        "thoiGianDongThau": "thoi_gian_dong_thau",
        "thoiGianGoiThau": "thoi_gian_goi_thau",
        "thoiGianHopDong": "thoi_gian_hop_dong",
        "thoiGianMoEhsdxtc": "thoi_gian_mo_ehsdxtc",
        "thoiGianMoThau": "thoi_gian_mo_thau",
        "thoiGianThucHien": "thoi_gian_thuc_hien",
        "thoiGianToChuc": "thoi_gian_to_chuc",
        "trangThai": "trang_thai",
        "trongSoKyThuat": "trong_so_ky_thuat",
        "tuyChonMuaThem": "tuy_chon_mua_them",
        "tyLeBaoDamHopDong": "ty_le_bao_dam_hop_dong",
        "updatedAt": "updated_at",
        "yeuCauThamDinhHsmt": "yeu_cau_tham_dinh_hsmt"
      }
    },
    "goi_thau_chuyen_gia": {
      "columns": [
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "chuyen_gia_id",
        "loai",
        "chuc_vu",
        "cong_viec",
        "created_at"
      ],
      "fieldMap": {
        "chuc_vu": "chucVu",
        "chuyen_gia_id": "chuyenGiaId",
        "cong_viec": "congViec",
        "created_at": "createdAt",
        "goi_thau_id": "goiThauId",
        "loai": "loai",
        "owner_id": "ownerId",
        "owner_type": "ownerType"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "chucVu": "chuc_vu",
        "chuyenGiaId": "chuyen_gia_id",
        "congViec": "cong_viec",
        "createdAt": "created_at",
        "goiThauId": "goi_thau_id",
        "loai": "loai",
        "ownerId": "owner_id",
        "ownerType": "owner_type"
      }
    },
    "goi_thau_gia_han": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "thoi_gian_dong_thau",
        "ly_do_gia_han",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "goi_thau_id": "goiThauId",
        "id": "id",
        "ly_do_gia_han": "lyDoGiaHan",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "thoi_gian_dong_thau": "thoiGianDongThau",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "goiThauId": "goi_thau_id",
        "id": "id",
        "lyDoGiaHan": "ly_do_gia_han",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "thoiGianDongThau": "thoi_gian_dong_thau",
        "updatedAt": "updated_at"
      }
    },
    "goi_thau_lam_ro": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "loai",
        "thoi_gian",
        "noi_dung",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "goi_thau_id": "goiThauId",
        "id": "id",
        "loai": "loai",
        "noi_dung": "noiDung",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "thoi_gian": "thoiGian",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "goiThauId": "goi_thau_id",
        "id": "id",
        "loai": "loai",
        "noiDung": "noi_dung",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "thoiGian": "thoi_gian",
        "updatedAt": "updated_at"
      }
    },
    "goi_thau_phan_lo": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "ma_phan_lo",
        "ten_phan_lo",
        "gia_tri_phan_lo",
        "bao_dam_du_thau",
        "thoi_gian_thuc_hien",
        "nha_thau_trung_thau_id",
        "gia_trung_thau",
        "thoi_gian_goi_thau",
        "thoi_gian_hop_dong",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "bao_dam_du_thau": "baoDamDuThau",
        "created_at": "createdAt",
        "gia_tri_phan_lo": "giaTriPhanLo",
        "gia_trung_thau": "giaTrungThau",
        "goi_thau_id": "goiThauId",
        "id": "id",
        "ma_phan_lo": "maPhanLo",
        "nha_thau_trung_thau_id": "nhaThauTrungThauId",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "ten_phan_lo": "tenPhanLo",
        "thoi_gian_goi_thau": "thoiGianGoiThau",
        "thoi_gian_hop_dong": "thoiGianHopDong",
        "thoi_gian_thuc_hien": "thoiGianThucHien",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "baoDamDuThau": "bao_dam_du_thau",
        "createdAt": "created_at",
        "giaTriPhanLo": "gia_tri_phan_lo",
        "giaTrungThau": "gia_trung_thau",
        "goiThauId": "goi_thau_id",
        "id": "id",
        "maPhanLo": "ma_phan_lo",
        "nhaThauTrungThauId": "nha_thau_trung_thau_id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "tenPhanLo": "ten_phan_lo",
        "thoiGianGoiThau": "thoi_gian_goi_thau",
        "thoiGianHopDong": "thoi_gian_hop_dong",
        "thoiGianThucHien": "thoi_gian_thuc_hien",
        "updatedAt": "updated_at"
      }
    },
    "goi_thau_tuy_chon_mua_them": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "hang_muc",
        "don_vi",
        "so_luong",
        "ty_le",
        "gia_tri_uoc_tinh",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "don_vi": "donVi",
        "gia_tri_uoc_tinh": "giaTriUocTinh",
        "goi_thau_id": "goiThauId",
        "hang_muc": "hangMuc",
        "id": "id",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "so_luong": "soLuong",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "ty_le": "tyLe",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "donVi": "don_vi",
        "giaTriUocTinh": "gia_tri_uoc_tinh",
        "goiThauId": "goi_thau_id",
        "hangMuc": "hang_muc",
        "id": "id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "soLuong": "so_luong",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "tyLe": "ty_le",
        "updatedAt": "updated_at"
      }
    },
    "hop_dong": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "phien_ban",
        "is_latest",
        "ten_hop_dong",
        "so_hop_dong",
        "ngay_ky",
        "chu_dau_tu_id",
        "nha_thau_id",
        "ke_hoach_id",
        "gia_tri",
        "loai_hop_dong",
        "thoi_gian_thuc_hien",
        "trang_thai_ho_so",
        "phan_loai",
        "co_qd_chi_dinh",
        "so_qd_chi_dinh",
        "ngay_qd_chi_dinh",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "chu_dau_tu_id": "chuDauTuId",
        "co_qd_chi_dinh": "coQdChiDinh",
        "created_at": "createdAt",
        "gia_tri": "giaTri",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "ke_hoach_id": "keHoachId",
        "loai_hop_dong": "loaiHopDong",
        "ngay_ky": "ngayKy",
        "ngay_qd_chi_dinh": "ngayQdChiDinh",
        "nha_thau_id": "nhaThauId",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phan_loai": "phanLoai",
        "phien_ban": "phienBan",
        "so_hop_dong": "soHopDong",
        "so_qd_chi_dinh": "soQdChiDinh",
        "sync_version": "syncVersion",
        "ten_hop_dong": "tenHopDong",
        "thoi_gian_thuc_hien": "soNgayThucHien",
        "trang_thai_ho_so": "trangThaiHoSo",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "chuDauTuId": "chu_dau_tu_id",
        "coQdChiDinh": "co_qd_chi_dinh",
        "createdAt": "created_at",
        "giaTri": "gia_tri",
        "id": "id",
        "isLatest": "is_latest",
        "keHoachId": "ke_hoach_id",
        "loaiHopDong": "loai_hop_dong",
        "ngayKy": "ngay_ky",
        "ngayQdChiDinh": "ngay_qd_chi_dinh",
        "nhaThauId": "nha_thau_id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "phanLoai": "phan_loai",
        "phienBan": "phien_ban",
        "rootId": "id_goc",
        "soHopDong": "so_hop_dong",
        "soNgayThucHien": "thoi_gian_thuc_hien",
        "soQdChiDinh": "so_qd_chi_dinh",
        "syncVersion": "sync_version",
        "tenHopDong": "ten_hop_dong",
        "trangThaiHoSo": "trang_thai_ho_so",
        "updatedAt": "updated_at"
      }
    },
    "hop_dong_goi_thau": {
      "columns": [
        "owner_id",
        "owner_type",
        "hop_dong_id",
        "goi_thau_id",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "goi_thau_id": "goiThauId",
        "hop_dong_id": "hopDongId",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "goiThauId": "goi_thau_id",
        "hopDongId": "hop_dong_id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "updatedAt": "updated_at"
      }
    },
    "ke_hoach_cong_viec": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "ke_hoach_id",
        "loai",
        "ten_cong_viec",
        "gia_tri",
        "don_vi_thuc_hien",
        "van_ban_phe_duyet",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "don_vi_thuc_hien": "donViThucHien",
        "gia_tri": "giaTri",
        "id": "id",
        "ke_hoach_id": "keHoachId",
        "loai": "loai",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "ten_cong_viec": "tenCongViec",
        "updated_at": "updatedAt",
        "van_ban_phe_duyet": "vanBanPheDuyet"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "donViThucHien": "don_vi_thuc_hien",
        "giaTri": "gia_tri",
        "id": "id",
        "keHoachId": "ke_hoach_id",
        "loai": "loai",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "tenCongViec": "ten_cong_viec",
        "updatedAt": "updated_at",
        "vanBanPheDuyet": "van_ban_phe_duyet"
      }
    },
    "ke_hoach_lcnt": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "ma_ke_hoach",
        "ma_du_an",
        "phien_ban",
        "is_latest",
        "ten_ke_hoach",
        "ten_du_an_du_toan",
        "loai_hinh_mua_sam",
        "chu_dau_tu_id",
        "don_vi_trinh_cdt",
        "ten_viet_tat_don_vi_trinh",
        "tong_muc_dau_tu",
        "is_tong_muc_tu_dong",
        "ngay_phe_duyet",
        "quyet_dinh_phe_duyet",
        "thoi_gian_dang_tai",
        "nguon_von",
        "thoi_gian_du_an",
        "dia_diem_quy_mo",
        "thong_tin_khac",
        "so_qd_phe_duyet_du_an",
        "ngay_qd_phe_duyet_du_an",
        "co_quan_phe_duyet_du_an",
        "phe_duyet",
        "ngay_trinh_du_toan",
        "ngay_phe_duyet_du_toan",
        "so_qd_phe_duyet_du_toan",
        "ngay_trinh_ke_hoach",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "chu_dau_tu_id": "chuDauTuId",
        "co_quan_phe_duyet_du_an": "coQuanPheDuyetDuAn",
        "created_at": "createdAt",
        "dia_diem_quy_mo": "diaDiemQuyMo",
        "don_vi_trinh_cdt": "donViTrinhCdt",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "is_tong_muc_tu_dong": "isTongMucTuDong",
        "loai_hinh_mua_sam": "loaiHinhMuaSam",
        "ma_du_an": "maDuAn",
        "ma_ke_hoach": "maKeHoach",
        "ngay_phe_duyet": "ngayPheDuyet",
        "ngay_phe_duyet_du_toan": "ngayPheDuyetDuToan",
        "ngay_qd_phe_duyet_du_an": "ngayQdPheDuyetDuAn",
        "ngay_trinh_du_toan": "ngayTrinhDuToan",
        "ngay_trinh_ke_hoach": "ngayTrinhKeHoach",
        "nguon_von": "nguonVon",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phe_duyet": "pheDuyet",
        "phien_ban": "phienBan",
        "quyet_dinh_phe_duyet": "quyetDinhPheDuyet",
        "so_qd_phe_duyet_du_an": "soQdPheDuyetDuAn",
        "so_qd_phe_duyet_du_toan": "soQdPheDuyetDuToan",
        "sync_version": "syncVersion",
        "ten_du_an_du_toan": "tenDuAnDuToan",
        "ten_ke_hoach": "tenKeHoach",
        "ten_viet_tat_don_vi_trinh": "tenVietTatDonViTrinh",
        "thoi_gian_dang_tai": "thoiGianDangMa",
        "thoi_gian_du_an": "thoiGianDuAn",
        "thong_tin_khac": "thongTinKhac",
        "tong_muc_dau_tu": "tongMucDauTu",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "chuDauTuId": "chu_dau_tu_id",
        "coQuanPheDuyetDuAn": "co_quan_phe_duyet_du_an",
        "createdAt": "created_at",
        "diaDiemQuyMo": "dia_diem_quy_mo",
        "donViTrinhCdt": "don_vi_trinh_cdt",
        "id": "id",
        "isLatest": "is_latest",
        "isTongMucTuDong": "is_tong_muc_tu_dong",
        "loaiHinhMuaSam": "loai_hinh_mua_sam",
        "maDuAn": "ma_du_an",
        "maKeHoach": "ma_ke_hoach",
        "ngayPheDuyet": "ngay_phe_duyet",
        "ngayPheDuyetDuToan": "ngay_phe_duyet_du_toan",
        "ngayQdPheDuyetDuAn": "ngay_qd_phe_duyet_du_an",
        "ngayTrinhDuToan": "ngay_trinh_du_toan",
        "ngayTrinhKeHoach": "ngay_trinh_ke_hoach",
        "nguonVon": "nguon_von",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "pheDuyet": "phe_duyet",
        "phienBan": "phien_ban",
        "quyetDinhPheDuyet": "quyet_dinh_phe_duyet",
        "rootId": "id_goc",
        "soQdPheDuyetDuAn": "so_qd_phe_duyet_du_an",
        "soQdPheDuyetDuToan": "so_qd_phe_duyet_du_toan",
        "syncVersion": "sync_version",
        "tenDuAnDuToan": "ten_du_an_du_toan",
        "tenKeHoach": "ten_ke_hoach",
        "tenVietTatDonViTrinh": "ten_viet_tat_don_vi_trinh",
        "thoiGianDangMa": "thoi_gian_dang_tai",
        "thoiGianDuAn": "thoi_gian_du_an",
        "thongTinKhac": "thong_tin_khac",
        "tongMucDauTu": "tong_muc_dau_tu",
        "updatedAt": "updated_at"
      }
    },
    "ma_tran_phan_quyen": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "emp_id",
        "kehoach",
        "goithau",
        "chudautu",
        "nhathau",
        "chuyengia",
        "hopdong",
        "thongtinmothau",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "chudautu": "chudautu",
        "chuyengia": "chuyengia",
        "created_at": "createdAt",
        "emp_id": "empId",
        "goithau": "goithau",
        "hopdong": "hopdong",
        "id": "id",
        "kehoach": "kehoach",
        "nhathau": "nhathau",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sync_version": "syncVersion",
        "thongtinmothau": "thongtinmothau",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "chudautu": "chudautu",
        "chuyengia": "chuyengia",
        "createdAt": "created_at",
        "empId": "emp_id",
        "goithau": "goithau",
        "hopdong": "hopdong",
        "id": "id",
        "kehoach": "kehoach",
        "nhathau": "nhathau",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "syncVersion": "sync_version",
        "thongtinmothau": "thongtinmothau",
        "updatedAt": "updated_at"
      }
    },
    "nha_thau": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_goc",
        "phien_ban",
        "is_latest",
        "ma_nha_thau",
        "ten_nha_thau",
        "ten_viet_tat",
        "loai_nha_thau",
        "ma_so_thue",
        "nguoi_dai_dien",
        "danh_xung",
        "so_dien_thoai",
        "email",
        "dia_chi",
        "dia_chi_goc",
        "so_tai_khoan",
        "noi_mo_tai_khoan",
        "ma_ngan_hang",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "danh_xung": "danhXung",
        "dia_chi": "diaChi",
        "dia_chi_goc": "diaChiGoc",
        "email": "email",
        "id": "id",
        "id_goc": "rootId",
        "is_latest": "isLatest",
        "loai_nha_thau": "loaiNhaThau",
        "ma_ngan_hang": "maNganHang",
        "ma_nha_thau": "maNhaThau",
        "ma_so_thue": "maSoThue",
        "nguoi_dai_dien": "nguoiDaiDien",
        "noi_mo_tai_khoan": "noiMoTaiKhoan",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "phien_ban": "phienBan",
        "so_dien_thoai": "soDienThoai",
        "so_tai_khoan": "soTaiKhoan",
        "sync_version": "syncVersion",
        "ten_nha_thau": "tenNhaThau",
        "ten_viet_tat": "tenVietTat",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "danhXung": "danh_xung",
        "diaChi": "dia_chi",
        "diaChiGoc": "dia_chi_goc",
        "email": "email",
        "id": "id",
        "isLatest": "is_latest",
        "loaiNhaThau": "loai_nha_thau",
        "maNganHang": "ma_ngan_hang",
        "maNhaThau": "ma_nha_thau",
        "maSoThue": "ma_so_thue",
        "nguoiDaiDien": "nguoi_dai_dien",
        "noiMoTaiKhoan": "noi_mo_tai_khoan",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "phienBan": "phien_ban",
        "rootId": "id_goc",
        "soDienThoai": "so_dien_thoai",
        "soTaiKhoan": "so_tai_khoan",
        "syncVersion": "sync_version",
        "tenNhaThau": "ten_nha_thau",
        "tenVietTat": "ten_viet_tat",
        "updatedAt": "updated_at"
      }
    },
    "nha_thau_lien_danh_thanh_vien": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "nha_thau_id",
        "ten_nha_thau",
        "ma_so_thue",
        "vai_tro",
        "nguoi_dai_dien",
        "danh_xung",
        "so_dien_thoai",
        "email",
        "dia_chi",
        "dia_chi_goc",
        "so_tai_khoan",
        "noi_mo_tai_khoan",
        "ma_ngan_hang",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "danh_xung": "danhXung",
        "dia_chi": "diaChi",
        "dia_chi_goc": "diaChiGoc",
        "email": "email",
        "id": "id",
        "ma_ngan_hang": "maNganHang",
        "ma_so_thue": "maSoThue",
        "nguoi_dai_dien": "nguoiDaiDien",
        "nha_thau_id": "nhaThauId",
        "noi_mo_tai_khoan": "noiMoTaiKhoan",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "so_dien_thoai": "soDienThoai",
        "so_tai_khoan": "soTaiKhoan",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "ten_nha_thau": "tenNhaThau",
        "updated_at": "updatedAt",
        "vai_tro": "vaiTro"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "danhXung": "danh_xung",
        "diaChi": "dia_chi",
        "diaChiGoc": "dia_chi_goc",
        "email": "email",
        "id": "id",
        "maNganHang": "ma_ngan_hang",
        "maSoThue": "ma_so_thue",
        "nguoiDaiDien": "nguoi_dai_dien",
        "nhaThauId": "nha_thau_id",
        "noiMoTaiKhoan": "noi_mo_tai_khoan",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "soDienThoai": "so_dien_thoai",
        "soTaiKhoan": "so_tai_khoan",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "tenNhaThau": "ten_nha_thau",
        "updatedAt": "updated_at",
        "vaiTro": "vai_tro"
      }
    },
    "phan_cong_nhan_su": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "id_nhan_vien",
        "id_muc_tieu",
        "loai_doi_tuong",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "id": "id",
        "id_muc_tieu": "targetId",
        "id_nhan_vien": "empId",
        "loai_doi_tuong": "type",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sync_version": "syncVersion",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "empId": "id_nhan_vien",
        "id": "id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "syncVersion": "sync_version",
        "targetId": "id_muc_tieu",
        "type": "loai_doi_tuong",
        "updatedAt": "updated_at"
      }
    },
    "sync_metadata": {
      "columns": [
        "owner_id",
        "current_version",
        "updated_at"
      ],
      "fieldMap": {
        "current_version": "currentVersion",
        "owner_id": "ownerId",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "currentVersion": "current_version",
        "ownerId": "owner_id",
        "updatedAt": "updated_at"
      }
    },
    "sync_mutations": {
      "columns": [
        "owner_id",
        "client_mutation_id",
        "response_json",
        "created_at"
      ],
      "fieldMap": {
        "client_mutation_id": "clientMutationId",
        "created_at": "createdAt",
        "owner_id": "ownerId",
        "response_json": "responseJson"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "clientMutationId": "client_mutation_id",
        "createdAt": "created_at",
        "ownerId": "owner_id",
        "responseJson": "response_json"
      }
    },
    "tai_khoan": {
      "columns": [
        "id",
        "ten_dang_nhap",
        "mat_khau",
        "ho_ten",
        "vai_tro",
        "email",
        "token_phien",
        "anh_dai_dien",
        "goi_dich_vu_id",
        "ngay_bat_dau_goi",
        "ngay_het_han_goi",
        "han_su_dung_token",
        "thong_tin_thiet_bi_cuoi",
        "da_xac_minh",
        "ma_xac_minh",
        "han_xac_minh",
        "google_id",
        "username_da_dat",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "anh_dai_dien": "anhDaiDien",
        "created_at": "createdAt",
        "da_xac_minh": "daXacMinh",
        "email": "email",
        "goi_dich_vu_id": "goiDichVuId",
        "google_id": "googleId",
        "han_su_dung_token": "hanSuDungToken",
        "han_xac_minh": "hanXacMinh",
        "ho_ten": "hoTen",
        "id": "id",
        "ma_xac_minh": "maXacMinh",
        "mat_khau": "matKhau",
        "ngay_bat_dau_goi": "ngayBatDauGoi",
        "ngay_het_han_goi": "ngayHetHanGoi",
        "ten_dang_nhap": "tenDangNhap",
        "thong_tin_thiet_bi_cuoi": "thongTinThietBiCuoi",
        "token_phien": "tokenPhien",
        "updated_at": "updatedAt",
        "username_da_dat": "usernameDaDat",
        "vai_tro": "vaiTro"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "anhDaiDien": "anh_dai_dien",
        "createdAt": "created_at",
        "daXacMinh": "da_xac_minh",
        "email": "email",
        "goiDichVuId": "goi_dich_vu_id",
        "googleId": "google_id",
        "hanSuDungToken": "han_su_dung_token",
        "hanXacMinh": "han_xac_minh",
        "hoTen": "ho_ten",
        "id": "id",
        "maXacMinh": "ma_xac_minh",
        "matKhau": "mat_khau",
        "ngayBatDauGoi": "ngay_bat_dau_goi",
        "ngayHetHanGoi": "ngay_het_han_goi",
        "tenDangNhap": "ten_dang_nhap",
        "thongTinThietBiCuoi": "thong_tin_thiet_bi_cuoi",
        "tokenPhien": "token_phien",
        "updatedAt": "updated_at",
        "usernameDaDat": "username_da_dat",
        "vaiTro": "vai_tro"
      }
    },
    "thanh_vien_to_chuc": {
      "columns": [
        "user_id",
        "to_chuc_id",
        "vai_tro_trong_to_chuc",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "to_chuc_id": "toChucId",
        "updated_at": "updatedAt",
        "user_id": "userId",
        "vai_tro_trong_to_chuc": "vaiTroTrongToChuc"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "toChucId": "to_chuc_id",
        "updatedAt": "updated_at",
        "userId": "user_id",
        "vaiTroTrongToChuc": "vai_tro_trong_to_chuc"
      }
    },
    "thong_tin_mo_thau": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "goi_thau_id",
        "nha_thau_id",
        "ma_phan_lo",
        "ten_phan_lo",
        "ma_dinh_danh",
        "gia_du_thau",
        "dam_bao_du_thau",
        "hieu_luc_dam_bao",
        "hieu_luc_hsdxt",
        "ty_le_giam_gia",
        "gia_sau_giam_gia",
        "hieu_luc_hsdt",
        "gia_tri_dam_bao",
        "hieu_luc_bao_dam_ngay",
        "thoi_gian_thuc_hien",
        "ten_nha_thau",
        "loai_nha_thau",
        "danh_gia_hop_le",
        "danh_gia_nang_luc",
        "danh_gia_ky_thuat",
        "danh_gia_tai_chinh",
        "danh_gia_ket_luan",
        "ly_do_truot",
        "lam_ro_hop_le",
        "lam_ro_nang_luc",
        "lam_ro_ky_thuat",
        "lam_ro_tai_chinh",
        "nguyen_nhan_khong_dat_hop_le",
        "nguyen_nhan_khong_dat_nang_luc",
        "nguyen_nhan_khong_dat_ky_thuat",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "dam_bao_du_thau": "damBaoDuThau",
        "danh_gia_hop_le": "danhGiaHopLe",
        "danh_gia_ket_luan": "danhGiaKetLuan",
        "danh_gia_ky_thuat": "danhGiaKyThuat",
        "danh_gia_nang_luc": "danhGiaNangLuc",
        "danh_gia_tai_chinh": "danhGiaTaiChinh",
        "gia_du_thau": "giaDuThau",
        "gia_sau_giam_gia": "giaSauGiamGia",
        "gia_tri_dam_bao": "giaTriDamBao",
        "goi_thau_id": "goiThauId",
        "hieu_luc_bao_dam_ngay": "hieuLucBaoDamNgay",
        "hieu_luc_dam_bao": "hieuLucDamBao",
        "hieu_luc_hsdt": "hieuLucHsdt",
        "hieu_luc_hsdxt": "hieuLucHsdxt",
        "id": "id",
        "lam_ro_hop_le": "lamRoHopLe",
        "lam_ro_ky_thuat": "lamRoKyThuat",
        "lam_ro_nang_luc": "lamRoNangLuc",
        "lam_ro_tai_chinh": "lamRoTaiChinh",
        "loai_nha_thau": "loaiNhaThau",
        "ly_do_truot": "lyDoTruot",
        "ma_dinh_danh": "maDinhDanh",
        "ma_phan_lo": "maPhanLo",
        "nguyen_nhan_khong_dat_hop_le": "nguyenNhanKhongDatHopLe",
        "nguyen_nhan_khong_dat_ky_thuat": "nguyenNhanKhongDatKyThuat",
        "nguyen_nhan_khong_dat_nang_luc": "nguyenNhanKhongDatNangLuc",
        "nha_thau_id": "nhaThauId",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sync_version": "syncVersion",
        "ten_nha_thau": "tenNhaThau",
        "ten_phan_lo": "tenPhanLo",
        "thoi_gian_thuc_hien": "thoiGianThucHien",
        "ty_le_giam_gia": "tyLeGiamGia",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "damBaoDuThau": "dam_bao_du_thau",
        "danhGiaHopLe": "danh_gia_hop_le",
        "danhGiaKetLuan": "danh_gia_ket_luan",
        "danhGiaKyThuat": "danh_gia_ky_thuat",
        "danhGiaNangLuc": "danh_gia_nang_luc",
        "danhGiaTaiChinh": "danh_gia_tai_chinh",
        "giaDuThau": "gia_du_thau",
        "giaSauGiamGia": "gia_sau_giam_gia",
        "giaTriDamBao": "gia_tri_dam_bao",
        "goiThauId": "goi_thau_id",
        "hieuLucBaoDamNgay": "hieu_luc_bao_dam_ngay",
        "hieuLucDamBao": "hieu_luc_dam_bao",
        "hieuLucHsdt": "hieu_luc_hsdt",
        "hieuLucHsdxt": "hieu_luc_hsdxt",
        "id": "id",
        "lamRoHopLe": "lam_ro_hop_le",
        "lamRoKyThuat": "lam_ro_ky_thuat",
        "lamRoNangLuc": "lam_ro_nang_luc",
        "lamRoTaiChinh": "lam_ro_tai_chinh",
        "loaiNhaThau": "loai_nha_thau",
        "lyDoTruot": "ly_do_truot",
        "maDinhDanh": "ma_dinh_danh",
        "maPhanLo": "ma_phan_lo",
        "nguyenNhanKhongDatHopLe": "nguyen_nhan_khong_dat_hop_le",
        "nguyenNhanKhongDatKyThuat": "nguyen_nhan_khong_dat_ky_thuat",
        "nguyenNhanKhongDatNangLuc": "nguyen_nhan_khong_dat_nang_luc",
        "nhaThauId": "nha_thau_id",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "syncVersion": "sync_version",
        "tenNhaThau": "ten_nha_thau",
        "tenPhanLo": "ten_phan_lo",
        "thoiGianThucHien": "thoi_gian_thuc_hien",
        "tyLeGiamGia": "ty_le_giam_gia",
        "updatedAt": "updated_at"
      }
    },
    "thong_tin_mo_thau_lien_danh_thanh_vien": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "thong_tin_mo_thau_id",
        "ten_nha_thau",
        "ma_so_thue",
        "vai_tro",
        "nguoi_dai_dien",
        "danh_xung",
        "so_dien_thoai",
        "email",
        "dia_chi",
        "dia_chi_goc",
        "so_tai_khoan",
        "noi_mo_tai_khoan",
        "ma_ngan_hang",
        "sort_order",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "danh_xung": "danhXung",
        "dia_chi": "diaChi",
        "dia_chi_goc": "diaChiGoc",
        "email": "email",
        "id": "id",
        "ma_ngan_hang": "maNganHang",
        "ma_so_thue": "maSoThue",
        "nguoi_dai_dien": "nguoiDaiDien",
        "noi_mo_tai_khoan": "noiMoTaiKhoan",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "so_dien_thoai": "soDienThoai",
        "so_tai_khoan": "soTaiKhoan",
        "sort_order": "sortOrder",
        "sync_version": "syncVersion",
        "ten_nha_thau": "tenNhaThau",
        "thong_tin_mo_thau_id": "thongTinMoThauId",
        "updated_at": "updatedAt",
        "vai_tro": "vaiTro"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "danhXung": "danh_xung",
        "diaChi": "dia_chi",
        "diaChiGoc": "dia_chi_goc",
        "email": "email",
        "id": "id",
        "maNganHang": "ma_ngan_hang",
        "maSoThue": "ma_so_thue",
        "nguoiDaiDien": "nguoi_dai_dien",
        "noiMoTaiKhoan": "noi_mo_tai_khoan",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "soDienThoai": "so_dien_thoai",
        "soTaiKhoan": "so_tai_khoan",
        "sortOrder": "sort_order",
        "syncVersion": "sync_version",
        "tenNhaThau": "ten_nha_thau",
        "thongTinMoThauId": "thong_tin_mo_thau_id",
        "updatedAt": "updated_at",
        "vaiTro": "vai_tro"
      }
    },
    "to_chuc": {
      "columns": [
        "id",
        "ten_to_chuc",
        "quan_ly_id",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "created_at": "createdAt",
        "id": "id",
        "quan_ly_id": "quanLyId",
        "ten_to_chuc": "tenToChuc",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "createdAt": "created_at",
        "id": "id",
        "quanLyId": "quan_ly_id",
        "tenToChuc": "ten_to_chuc",
        "updatedAt": "updated_at"
      }
    },
    "trang_thai_ho_so_giay": {
      "columns": [
        "id",
        "owner_id",
        "owner_type",
        "name",
        "color",
        "sync_version",
        "created_at",
        "updated_at"
      ],
      "fieldMap": {
        "color": "color",
        "created_at": "createdAt",
        "id": "id",
        "name": "name",
        "owner_id": "ownerId",
        "owner_type": "ownerType",
        "sync_version": "syncVersion",
        "updated_at": "updatedAt"
      },
      "jsonFields": [],
      "reverseFieldMap": {
        "color": "color",
        "createdAt": "created_at",
        "id": "id",
        "name": "name",
        "ownerId": "owner_id",
        "ownerType": "owner_type",
        "syncVersion": "sync_version",
        "updatedAt": "updated_at"
      }
    }
  },
  "version": 1
};

export const CLIENT_TABLE_MAP = SCHEMA_CONTRACT.clientTableMap;
export const COMMON_FIELD_NAME_OVERRIDES = SCHEMA_CONTRACT.commonFieldMap;
export const FIELD_MAP_BY_TABLE = Object.fromEntries(
  Object.entries(SCHEMA_CONTRACT.tables).map(([table, spec]) => [table, spec.fieldMap || {}])
);

export const resolveSchemaTable = (type) => CLIENT_TABLE_MAP[type] || type;
